// Code generated by BobGen sql v0.50.0. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package dbinfo

import "github.com/aarondl/opt/null"

var Transactions = Table[
	transactionColumns,
	transactionIndexes,
	transactionForeignKeys,
	transactionUniques,
	transactionChecks,
]{
	Schema: "",
	Name:   "transactions",
	Columns: transactionColumns{
		ID: column{
			Name:      "id",
			DBType:    "uuid",
			Default:   "",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		Note: column{
			Name:      "note",
			DBType:    "text",
			Default:   "''::text",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		Amount: column{
			Name:      "amount",
			DBType:    "bigint",
			Default:   "",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		Type: column{
			Name:      "type",
			DBType:    "text",
			Default:   "",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		Category: column{
			Name:      "category",
			DBType:    "text",
			Default:   "",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		Owner: column{
			Name:      "owner",
			DBType:    "text",
			Default:   "",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		RawText: column{
			Name:      "raw_text",
			DBType:    "text",
			Default:   "",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		CreatedAt: column{
			Name:      "created_at",
			DBType:    "timestamp with time zone",
			Default:   "",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		InsertedAt: column{
			Name:      "inserted_at",
			DBType:    "timestamp with time zone",
			Default:   "now()",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
	},
	Indexes: transactionIndexes{
		TransactionsPkey: index{
			Type: "btree",
			Name: "transactions_pkey",
			Columns: []indexColumn{
				{
					Name:         "id",
					Desc:         null.FromCond(false, true),
					IsExpression: false,
				},
			},
			Unique:        true,
			Comment:       "",
			NullsFirst:    []bool{false},
			NullsDistinct: false,
			Where:         "",
			Include:       []string{},
		},
		IdxTransactionsCreatedAt: index{
			Type: "btree",
			Name: "idx_transactions_created_at",
			Columns: []indexColumn{
				{
					Name:         "created_at",
					Desc:         null.FromCond(false, true),
					IsExpression: false,
				},
			},
			Unique:        false,
			Comment:       "",
			NullsFirst:    []bool{false},
			NullsDistinct: false,
			Where:         "",
			Include:       []string{},
		},
		TransactionsDedupeKey: index{
			Type: "btree",
			Name: "transactions_dedupe_key",
			Columns: []indexColumn{
				{
					Name:         "created_at",
					Desc:         null.FromCond(false, true),
					IsExpression: false,
				},
				{
					Name:         "md5(raw_text)",
					Desc:         null.FromCond(false, true),
					IsExpression: true,
				},
			},
			Unique:        true,
			Comment:       "",
			NullsFirst:    []bool{false, false},
			NullsDistinct: false,
			Where:         "",
			Include:       []string{},
		},
	},
	PrimaryKey: &constraint{
		Name:    "transactions_pkey",
		Columns: []string{"id"},
		Comment: "",
	},

	Checks: transactionChecks{
		TransactionsAmountCheck: check{
			constraint: constraint{
				Name:    "transactions_amount_check",
				Columns: []string{"amount"},
				Comment: "",
			},
			Expression: "(amount > 0)",
		},
		TransactionsCategoryCheck: check{
			constraint: constraint{
				Name:    "transactions_category_check",
				Columns: []string{"category"},
				Comment: "",
			},
			Expression: "(category = ANY (ARRAY['food_drink'::text, 'entertainment'::text, 'shopping'::text, 'other'::text]))",
		},
		TransactionsOwnerCheck: check{
			constraint: constraint{
				Name:    "transactions_owner_check",
				Columns: []string{"owner"},
				Comment: "",
			},
			Expression: "(owner = ANY (ARRAY['van'::text, 'manh'::text]))",
		},
		TransactionsTypeCheck: check{
			constraint: constraint{
				Name:    "transactions_type_check",
				Columns: []string{"type"},
				Comment: "",
			},
			Expression: "(type = ANY (ARRAY['income'::text, 'expense'::text]))",
		},
	},
	Comment: "",
}

type transactionColumns struct {
	ID         column
	Note       column
	Amount     column
	Type       column
	Category   column
	Owner      column
	RawText    column
	CreatedAt  column
	InsertedAt column
}

func (c transactionColumns) AsSlice() []column {
	return []column{
		c.ID, c.Note, c.Amount, c.Type, c.Category, c.Owner, c.RawText, c.CreatedAt, c.InsertedAt,
	}
}

type transactionIndexes struct {
	TransactionsPkey         index
	IdxTransactionsCreatedAt index
	TransactionsDedupeKey    index
}

func (i transactionIndexes) AsSlice() []index {
	return []index{
		i.TransactionsPkey, i.IdxTransactionsCreatedAt, i.TransactionsDedupeKey,
	}
}

type transactionForeignKeys struct{}

func (f transactionForeignKeys) AsSlice() []foreignKey {
	return []foreignKey{}
}

type transactionUniques struct{}

func (u transactionUniques) AsSlice() []constraint {
	return []constraint{}
}

type transactionChecks struct {
	TransactionsAmountCheck   check
	TransactionsCategoryCheck check
	TransactionsOwnerCheck    check
	TransactionsTypeCheck     check
}

func (c transactionChecks) AsSlice() []check {
	return []check{
		c.TransactionsAmountCheck, c.TransactionsCategoryCheck, c.TransactionsOwnerCheck, c.TransactionsTypeCheck,
	}
}
