// Code generated by BobGen sql v0.50.0. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package model

import (
	"context"
	"io"
	"time"

	"github.com/stephenafamo/bob"
	"github.com/stephenafamo/bob/dialect/psql"
	"github.com/stephenafamo/bob/dialect/psql/dialect"
	"github.com/stephenafamo/bob/dialect/psql/dm"
	"github.com/stephenafamo/bob/dialect/psql/sm"
	"github.com/stephenafamo/bob/dialect/psql/um"
	"github.com/stephenafamo/bob/expr"
	"github.com/stephenafamo/scan"
)

// Transaction is an object representing the database table.
type Transaction struct {
	ID         string    `db:"id,pk" `
	Note       string    `db:"note" `
	Amount     int64     `db:"amount" `
	Type       string    `db:"type" `
	Category   string    `db:"category" `
	Owner      string    `db:"owner" `
	RawText    string    `db:"raw_text" `
	CreatedAt  time.Time `db:"created_at" `
	InsertedAt time.Time `db:"inserted_at" `
}

// TransactionSlice is an alias for a slice of pointers to Transaction.
// This should almost always be used instead of []*Transaction.
type TransactionSlice []*Transaction

// Transactions contains methods to work with the transactions table
var Transactions = psql.NewTablex[*Transaction, TransactionSlice, *TransactionSetter]("", "transactions", buildTransactionColumns("transactions"), transactionScanMapper)

// TransactionsQuery is a query on the transactions table
type TransactionsQuery = *psql.ViewQuery[*Transaction, TransactionSlice]

func buildTransactionColumns(tableName string) transactionColumns {
	columnsExpr := expr.NewColumnsExpr(
		"id", "note", "amount", "type", "category", "owner", "raw_text", "created_at", "inserted_at",
	)

	if tableName != "" {
		columnsExpr = columnsExpr.WithParent(tableName)
	}

	return transactionColumns{
		ColumnsExpr: columnsExpr,
		tableAlias:  tableName,
		ID:          buildTransactionColumn(tableName, "id"),
		Note:        buildTransactionColumn(tableName, "note"),
		Amount:      buildTransactionColumn(tableName, "amount"),
		Type:        buildTransactionColumn(tableName, "type"),
		Category:    buildTransactionColumn(tableName, "category"),
		Owner:       buildTransactionColumn(tableName, "owner"),
		RawText:     buildTransactionColumn(tableName, "raw_text"),
		CreatedAt:   buildTransactionColumn(tableName, "created_at"),
		InsertedAt:  buildTransactionColumn(tableName, "inserted_at"),
	}
}

type transactionColumns struct {
	expr.ColumnsExpr
	tableAlias string
	ID         transactionColumn
	Note       transactionColumn
	Amount     transactionColumn
	Type       transactionColumn
	Category   transactionColumn
	Owner      transactionColumn
	RawText    transactionColumn
	CreatedAt  transactionColumn
	InsertedAt transactionColumn
}

// Alias returns the current table alias for the columns set.
func (c transactionColumns) Alias() string {
	return c.tableAlias
}

// AliasedAs returns a copy of the columns set qualified by tableName.
func (transactionColumns) AliasedAs(tableName string) transactionColumns {
	return buildTransactionColumns(tableName)
}

// Unqualified returns a copy of the columns set without table qualification.
func (c transactionColumns) Unqualified() transactionColumns {
	return buildTransactionColumns("")
}

func buildTransactionColumn(alias, name string) transactionColumn {
	return transactionColumn{
		Expression: psql.Quote(alias, name),
		alias:      alias,
		name:       name,
	}
}

type transactionColumn struct {
	psql.Expression
	alias string
	name  string
}

// Name returns the unqualified column name.
func (c transactionColumn) Name() string {
	return c.name
}

// ShouldOmitParens prevents automatic parenthesis wrapping in expression builders.
func (c transactionColumn) ShouldOmitParens() bool {
	return true
}

// TransactionSetter is used for insert/upsert/update operations
// All values are optional, and do not have to be set
// Generated columns are not included
type TransactionSetter struct {
	ID         *string    `db:"id,pk" `
	Note       *string    `db:"note" `
	Amount     *int64     `db:"amount" `
	Type       *string    `db:"type" `
	Category   *string    `db:"category" `
	Owner      *string    `db:"owner" `
	RawText    *string    `db:"raw_text" `
	CreatedAt  *time.Time `db:"created_at" `
	InsertedAt *time.Time `db:"inserted_at" `
}

func (s TransactionSetter) SetColumns() []string {
	vals := make([]string, 0, 9)
	if s.ID != nil {
		vals = append(vals, "id")
	}
	if s.Note != nil {
		vals = append(vals, "note")
	}
	if s.Amount != nil {
		vals = append(vals, "amount")
	}
	if s.Type != nil {
		vals = append(vals, "type")
	}
	if s.Category != nil {
		vals = append(vals, "category")
	}
	if s.Owner != nil {
		vals = append(vals, "owner")
	}
	if s.RawText != nil {
		vals = append(vals, "raw_text")
	}
	if s.CreatedAt != nil {
		vals = append(vals, "created_at")
	}
	if s.InsertedAt != nil {
		vals = append(vals, "inserted_at")
	}
	return vals
}

func (s TransactionSetter) Overwrite(t *Transaction) {
	if s.ID != nil {
		t.ID = func() string {
			if s.ID == nil {
				return *new(string)
			}
			return *s.ID
		}()
	}
	if s.Note != nil {
		t.Note = func() string {
			if s.Note == nil {
				return *new(string)
			}
			return *s.Note
		}()
	}
	if s.Amount != nil {
		t.Amount = func() int64 {
			if s.Amount == nil {
				return *new(int64)
			}
			return *s.Amount
		}()
	}
	if s.Type != nil {
		t.Type = func() string {
			if s.Type == nil {
				return *new(string)
			}
			return *s.Type
		}()
	}
	if s.Category != nil {
		t.Category = func() string {
			if s.Category == nil {
				return *new(string)
			}
			return *s.Category
		}()
	}
	if s.Owner != nil {
		t.Owner = func() string {
			if s.Owner == nil {
				return *new(string)
			}
			return *s.Owner
		}()
	}
	if s.RawText != nil {
		t.RawText = func() string {
			if s.RawText == nil {
				return *new(string)
			}
			return *s.RawText
		}()
	}
	if s.CreatedAt != nil {
		t.CreatedAt = func() time.Time {
			if s.CreatedAt == nil {
				return *new(time.Time)
			}
			return *s.CreatedAt
		}()
	}
	if s.InsertedAt != nil {
		t.InsertedAt = func() time.Time {
			if s.InsertedAt == nil {
				return *new(time.Time)
			}
			return *s.InsertedAt
		}()
	}
}

func (s *TransactionSetter) Apply(q *dialect.InsertQuery) {
	q.AppendHooks(func(ctx context.Context, exec bob.Executor) (context.Context, error) {
		return Transactions.BeforeInsertHooks.RunHooks(ctx, exec, s)
	})

	q.AppendValues(
		bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
			if s.ID == nil {
				return psql.Raw("DEFAULT").WriteSQL(ctx, w, d, start)
			}
			return psql.Arg(func() string {
				if s.ID == nil {
					return *new(string)
				}
				return *s.ID
			}()).WriteSQL(ctx, w, d, start)
		}), bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
			if s.Note == nil {
				return psql.Raw("DEFAULT").WriteSQL(ctx, w, d, start)
			}
			return psql.Arg(func() string {
				if s.Note == nil {
					return *new(string)
				}
				return *s.Note
			}()).WriteSQL(ctx, w, d, start)
		}), bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
			if s.Amount == nil {
				return psql.Raw("DEFAULT").WriteSQL(ctx, w, d, start)
			}
			return psql.Arg(func() int64 {
				if s.Amount == nil {
					return *new(int64)
				}
				return *s.Amount
			}()).WriteSQL(ctx, w, d, start)
		}), bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
			if s.Type == nil {
				return psql.Raw("DEFAULT").WriteSQL(ctx, w, d, start)
			}
			return psql.Arg(func() string {
				if s.Type == nil {
					return *new(string)
				}
				return *s.Type
			}()).WriteSQL(ctx, w, d, start)
		}), bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
			if s.Category == nil {
				return psql.Raw("DEFAULT").WriteSQL(ctx, w, d, start)
			}
			return psql.Arg(func() string {
				if s.Category == nil {
					return *new(string)
				}
				return *s.Category
			}()).WriteSQL(ctx, w, d, start)
		}), bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
			if s.Owner == nil {
				return psql.Raw("DEFAULT").WriteSQL(ctx, w, d, start)
			}
			return psql.Arg(func() string {
				if s.Owner == nil {
					return *new(string)
				}
				return *s.Owner
			}()).WriteSQL(ctx, w, d, start)
		}), bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
			if s.RawText == nil {
				return psql.Raw("DEFAULT").WriteSQL(ctx, w, d, start)
			}
			return psql.Arg(func() string {
				if s.RawText == nil {
					return *new(string)
				}
				return *s.RawText
			}()).WriteSQL(ctx, w, d, start)
		}), bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
			if s.CreatedAt == nil {
				return psql.Raw("DEFAULT").WriteSQL(ctx, w, d, start)
			}
			return psql.Arg(func() time.Time {
				if s.CreatedAt == nil {
					return *new(time.Time)
				}
				return *s.CreatedAt
			}()).WriteSQL(ctx, w, d, start)
		}), bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
			if s.InsertedAt == nil {
				return psql.Raw("DEFAULT").WriteSQL(ctx, w, d, start)
			}
			return psql.Arg(func() time.Time {
				if s.InsertedAt == nil {
					return *new(time.Time)
				}
				return *s.InsertedAt
			}()).WriteSQL(ctx, w, d, start)
		}))
}

func (s TransactionSetter) UpdateMod() bob.Mod[*dialect.UpdateQuery] {
	return um.Set(s.Expressions()...)
}

func (s TransactionSetter) Expressions(prefix ...string) []bob.Expression {
	exprs := make([]bob.Expression, 0, 9)

	if s.ID != nil {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "id")...),
			psql.Arg(s.ID),
		}})
	}

	if s.Note != nil {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "note")...),
			psql.Arg(s.Note),
		}})
	}

	if s.Amount != nil {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "amount")...),
			psql.Arg(s.Amount),
		}})
	}

	if s.Type != nil {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "type")...),
			psql.Arg(s.Type),
		}})
	}

	if s.Category != nil {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "category")...),
			psql.Arg(s.Category),
		}})
	}

	if s.Owner != nil {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "owner")...),
			psql.Arg(s.Owner),
		}})
	}

	if s.RawText != nil {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "raw_text")...),
			psql.Arg(s.RawText),
		}})
	}

	if s.CreatedAt != nil {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "created_at")...),
			psql.Arg(s.CreatedAt),
		}})
	}

	if s.InsertedAt != nil {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "inserted_at")...),
			psql.Arg(s.InsertedAt),
		}})
	}

	return exprs
}

// scan.Mapper[*T] without reflection: maps columns to fields by index.
func transactionScanMapper(ctx context.Context, cols []string) (scan.BeforeFunc, func(any) (*Transaction, error)) {
	// resolve the column positions once per query, not per row
	type target struct {
		idx int
		dst func(o *Transaction) any
	}
	targets := make([]target, 0, 9)
	for i, col := range cols {
		switch col {
		case "id":
			targets = append(targets, target{i, func(o *Transaction) any { return &o.ID }})
		case "note":
			targets = append(targets, target{i, func(o *Transaction) any { return &o.Note }})
		case "amount":
			targets = append(targets, target{i, func(o *Transaction) any { return &o.Amount }})
		case "type":
			targets = append(targets, target{i, func(o *Transaction) any { return &o.Type }})
		case "category":
			targets = append(targets, target{i, func(o *Transaction) any { return &o.Category }})
		case "owner":
			targets = append(targets, target{i, func(o *Transaction) any { return &o.Owner }})
		case "raw_text":
			targets = append(targets, target{i, func(o *Transaction) any { return &o.RawText }})
		case "created_at":
			targets = append(targets, target{i, func(o *Transaction) any { return &o.CreatedAt }})
		case "inserted_at":
			targets = append(targets, target{i, func(o *Transaction) any { return &o.InsertedAt }})
		}
	}

	return func(row *scan.Row) (any, error) {
			o := new(Transaction)
			for _, t := range targets {
				row.ScheduleScanByIndex(t.idx, t.dst(o))
			}
			return o, nil
		}, func(v any) (*Transaction, error) {
			return v.(*Transaction), nil
		}
}

// FindTransaction retrieves a single record by primary key
// If cols is empty Find will return all columns.
func FindTransaction(ctx context.Context, exec bob.Executor, IDPK string, cols ...string) (*Transaction, error) {
	if len(cols) == 0 {
		return Transactions.Query(
			sm.Where(Transactions.Columns.ID.EQ(psql.Arg(IDPK))),
		).One(ctx, exec)
	}

	return Transactions.Query(
		sm.Where(Transactions.Columns.ID.EQ(psql.Arg(IDPK))),
		sm.Columns(Transactions.Columns.Only(cols...)),
	).One(ctx, exec)
}

// TransactionExists checks the presence of a single record by primary key
func TransactionExists(ctx context.Context, exec bob.Executor, IDPK string) (bool, error) {
	return Transactions.Query(
		sm.Where(Transactions.Columns.ID.EQ(psql.Arg(IDPK))),
	).Exists(ctx, exec)
}

// AfterQueryHook is called after Transaction is retrieved from the database
func (o *Transaction) AfterQueryHook(ctx context.Context, exec bob.Executor, queryType bob.QueryType) error {
	var err error

	switch queryType {
	case bob.QueryTypeSelect:
		ctx, err = Transactions.AfterSelectHooks.RunHooks(ctx, exec, TransactionSlice{o})
	case bob.QueryTypeInsert:
		ctx, err = Transactions.AfterInsertHooks.RunHooks(ctx, exec, TransactionSlice{o})
	case bob.QueryTypeUpdate:
		ctx, err = Transactions.AfterUpdateHooks.RunHooks(ctx, exec, TransactionSlice{o})
	case bob.QueryTypeDelete:
		ctx, err = Transactions.AfterDeleteHooks.RunHooks(ctx, exec, TransactionSlice{o})
	case bob.QueryTypeMerge:
		ctx, err = Transactions.AfterMergeHooks.RunHooks(ctx, exec, TransactionSlice{o})
	}

	return err
}

// primaryKeyVals returns the primary key values of the Transaction
func (o *Transaction) primaryKeyVals() bob.Expression {
	return psql.Arg(o.ID)
}

func (o *Transaction) pkEQ() dialect.Expression {
	return psql.Quote("transactions", "id").EQ(bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
		return o.primaryKeyVals().WriteSQL(ctx, w, d, start)
	}))
}

// Update uses an executor to update the Transaction
func (o *Transaction) Update(ctx context.Context, exec bob.Executor, s *TransactionSetter) error {
	v, err := Transactions.Update(s.UpdateMod(), um.Where(o.pkEQ())).One(ctx, exec)
	if err != nil {
		return err
	}

	*o = *v

	return nil
}

// Delete deletes a single Transaction record with an executor
func (o *Transaction) Delete(ctx context.Context, exec bob.Executor) error {
	_, err := Transactions.Delete(dm.Where(o.pkEQ())).Exec(ctx, exec)
	return err
}

// Reload refreshes the Transaction using the executor
func (o *Transaction) Reload(ctx context.Context, exec bob.Executor) error {
	o2, err := Transactions.Query(
		sm.Where(Transactions.Columns.ID.EQ(psql.Arg(o.ID))),
	).One(ctx, exec)
	if err != nil {
		return err
	}

	*o = *o2

	return nil
}

// AfterQueryHook is called after TransactionSlice is retrieved from the database
func (o TransactionSlice) AfterQueryHook(ctx context.Context, exec bob.Executor, queryType bob.QueryType) error {
	var err error

	switch queryType {
	case bob.QueryTypeSelect:
		ctx, err = Transactions.AfterSelectHooks.RunHooks(ctx, exec, o)
	case bob.QueryTypeInsert:
		ctx, err = Transactions.AfterInsertHooks.RunHooks(ctx, exec, o)
	case bob.QueryTypeUpdate:
		ctx, err = Transactions.AfterUpdateHooks.RunHooks(ctx, exec, o)
	case bob.QueryTypeDelete:
		ctx, err = Transactions.AfterDeleteHooks.RunHooks(ctx, exec, o)
	case bob.QueryTypeMerge:
		ctx, err = Transactions.AfterMergeHooks.RunHooks(ctx, exec, o)
	}

	return err
}

func (o TransactionSlice) pkIN() dialect.Expression {
	if len(o) == 0 {
		return psql.Raw("NULL")
	}

	return psql.Quote("transactions", "id").In(bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
		pkPairs := make([]bob.Expression, len(o))
		for i, row := range o {
			pkPairs[i] = row.primaryKeyVals()
		}
		return bob.ExpressSlice(ctx, w, d, start, pkPairs, "", ", ", "")
	}))
}

// copyMatchingRows finds models in the given slice that have the same primary key
// then it first copies the existing relationships from the old model to the new model
// and then replaces the old model in the slice with the new model
func (o TransactionSlice) copyMatchingRows(from ...*Transaction) {
	fromByPK := make(map[string]*Transaction, len(from))
	for _, new := range from {
		// keep the first row for each key, like the nested loop did
		if _, ok := fromByPK[new.ID]; !ok {
			fromByPK[new.ID] = new
		}
	}

	for i, old := range o {
		new, ok := fromByPK[old.ID]
		if !ok {
			continue
		}

		o[i] = new
	}
}

// UpdateMod modifies an update query with "WHERE primary_key IN (o...)"
func (o TransactionSlice) UpdateMod() bob.Mod[*dialect.UpdateQuery] {
	return bob.ModFunc[*dialect.UpdateQuery](func(q *dialect.UpdateQuery) {
		q.AppendHooks(func(ctx context.Context, exec bob.Executor) (context.Context, error) {
			return Transactions.BeforeUpdateHooks.RunHooks(ctx, exec, o)
		})

		q.AppendLoader(bob.LoaderFunc(func(ctx context.Context, exec bob.Executor, retrieved any) error {
			var err error
			switch retrieved := retrieved.(type) {
			case *Transaction:
				o.copyMatchingRows(retrieved)
			case []*Transaction:
				o.copyMatchingRows(retrieved...)
			case TransactionSlice:
				o.copyMatchingRows(retrieved...)
			default:
				// If the retrieved value is not a Transaction or a slice of Transaction
				// then run the AfterUpdateHooks on the slice
				_, err = Transactions.AfterUpdateHooks.RunHooks(ctx, exec, o)
			}

			return err
		}))

		q.AppendWhere(o.pkIN())
	})
}

// DeleteMod modifies an delete query with "WHERE primary_key IN (o...)"
func (o TransactionSlice) DeleteMod() bob.Mod[*dialect.DeleteQuery] {
	return bob.ModFunc[*dialect.DeleteQuery](func(q *dialect.DeleteQuery) {
		q.AppendHooks(func(ctx context.Context, exec bob.Executor) (context.Context, error) {
			return Transactions.BeforeDeleteHooks.RunHooks(ctx, exec, o)
		})

		q.AppendLoader(bob.LoaderFunc(func(ctx context.Context, exec bob.Executor, retrieved any) error {
			var err error
			switch retrieved := retrieved.(type) {
			case *Transaction:
				o.copyMatchingRows(retrieved)
			case []*Transaction:
				o.copyMatchingRows(retrieved...)
			case TransactionSlice:
				o.copyMatchingRows(retrieved...)
			default:
				// If the retrieved value is not a Transaction or a slice of Transaction
				// then run the AfterDeleteHooks on the slice
				_, err = Transactions.AfterDeleteHooks.RunHooks(ctx, exec, o)
			}

			return err
		}))

		q.AppendWhere(o.pkIN())
	})
}

// MergeMod modifies a merge query to run BeforeMergeHooks and AfterMergeHooks
// and updates the slice with the returned rows.
func (o TransactionSlice) MergeMod() bob.Mod[*dialect.MergeQuery] {
	return bob.ModFunc[*dialect.MergeQuery](func(q *dialect.MergeQuery) {
		q.AppendHooks(func(ctx context.Context, exec bob.Executor) (context.Context, error) {
			return Transactions.BeforeMergeHooks.RunHooks(ctx, exec, o)
		})

		q.AppendLoader(bob.LoaderFunc(func(ctx context.Context, exec bob.Executor, retrieved any) error {
			var err error
			switch retrieved := retrieved.(type) {
			case *Transaction:
				o.copyMatchingRows(retrieved)
			case []*Transaction:
				o.copyMatchingRows(retrieved...)
			case TransactionSlice:
				o.copyMatchingRows(retrieved...)
			default:
				// If the retrieved value is not a Transaction or a slice of Transaction
				// then run the AfterMergeHooks on the slice
				_, err = Transactions.AfterMergeHooks.RunHooks(ctx, exec, o)
			}

			return err
		}))
	})
}

func (o TransactionSlice) UpdateAll(ctx context.Context, exec bob.Executor, vals TransactionSetter) error {
	if len(o) == 0 {
		return nil
	}

	_, err := Transactions.Update(vals.UpdateMod(), o.UpdateMod()).All(ctx, exec)
	return err
}

func (o TransactionSlice) DeleteAll(ctx context.Context, exec bob.Executor) error {
	if len(o) == 0 {
		return nil
	}

	_, err := Transactions.Delete(o.DeleteMod()).Exec(ctx, exec)
	return err
}

func (o TransactionSlice) ReloadAll(ctx context.Context, exec bob.Executor) error {
	if len(o) == 0 {
		return nil
	}

	o2, err := Transactions.Query(sm.Where(o.pkIN())).All(ctx, exec)
	if err != nil {
		return err
	}

	o.copyMatchingRows(o2...)

	return nil
}

type transactionWhere[Q psql.Filterable] struct {
	cols       transactionColumns
	ID         psql.WhereMod[Q, string]
	Note       psql.WhereMod[Q, string]
	Amount     psql.WhereMod[Q, int64]
	Type       psql.WhereMod[Q, string]
	Category   psql.WhereMod[Q, string]
	Owner      psql.WhereMod[Q, string]
	RawText    psql.WhereMod[Q, string]
	CreatedAt  psql.WhereMod[Q, time.Time]
	InsertedAt psql.WhereMod[Q, time.Time]
}

func (transactionWhere[Q]) AliasedAs(alias string) transactionWhere[Q] {
	return buildTransactionWhere[Q](buildTransactionColumns(alias))
}

func buildTransactionWhere[Q psql.Filterable](cols transactionColumns) transactionWhere[Q] {
	return transactionWhere[Q]{
		cols:       cols,
		ID:         psql.Where[Q, string](cols.ID.Expression),
		Note:       psql.Where[Q, string](cols.Note.Expression),
		Amount:     psql.Where[Q, int64](cols.Amount.Expression),
		Type:       psql.Where[Q, string](cols.Type.Expression),
		Category:   psql.Where[Q, string](cols.Category.Expression),
		Owner:      psql.Where[Q, string](cols.Owner.Expression),
		RawText:    psql.Where[Q, string](cols.RawText.Expression),
		CreatedAt:  psql.Where[Q, time.Time](cols.CreatedAt.Expression),
		InsertedAt: psql.Where[Q, time.Time](cols.InsertedAt.Expression),
	}
}
