// Code generated by BobGen sql v0.49.0. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package model

import (
	"context"
	"testing"
)

// Test that Group has a C field with count pointers for to-many relationships
func TestGroupCountStruct(t *testing.T) {
	var m Group
	_ = m.C // Verify C field exists

	// Verify UserGroups count field exists and is *int64
	var _ *int64 = m.C.UserGroups
}

// Test that Group has LoadCount methods for to-many relationships
func TestGroupLoadCountMethods(t *testing.T) {
	var m *Group
	var ms GroupSlice
	ctx := context.Background()

	// Verify LoadCountUserGroups method exists on single model
	_ = m.LoadCountUserGroups(ctx, nil)

	// Verify LoadCountUserGroups method exists on slice
	_ = ms.LoadCountUserGroups(ctx, nil)
}

// Test that SelectThenLoadCount has Group with methods for to-many relationships
func TestSelectThenLoadCountGroup(t *testing.T) {
	_ = SelectThenLoadCount.Group

	// Verify UserGroups loader exists
	_ = SelectThenLoadCount.Group.UserGroups
}

// Test that PreloadCount has Group with methods for to-many relationships
func TestPreloadCountGroup(t *testing.T) {
	_ = PreloadCount.Group

	// Verify UserGroups preloader exists and returns a Preloader
	_ = PreloadCount.Group.UserGroups()
}

// Test that Group has PreloadCount method
func TestGroupPreloadCountMethod(t *testing.T) {
	var m *Group

	_ = m.PreloadCount("UserGroups", 0)
}

// Test that User has a C field with count pointers for to-many relationships
func TestUserCountStruct(t *testing.T) {
	var m User
	_ = m.C // Verify C field exists

	// Verify UserGroups count field exists and is *int64
	var _ *int64 = m.C.UserGroups
}

// Test that User has LoadCount methods for to-many relationships
func TestUserLoadCountMethods(t *testing.T) {
	var m *User
	var ms UserSlice
	ctx := context.Background()

	// Verify LoadCountUserGroups method exists on single model
	_ = m.LoadCountUserGroups(ctx, nil)

	// Verify LoadCountUserGroups method exists on slice
	_ = ms.LoadCountUserGroups(ctx, nil)
}

// Test that SelectThenLoadCount has User with methods for to-many relationships
func TestSelectThenLoadCountUser(t *testing.T) {
	_ = SelectThenLoadCount.User

	// Verify UserGroups loader exists
	_ = SelectThenLoadCount.User.UserGroups
}

// Test that PreloadCount has User with methods for to-many relationships
func TestPreloadCountUser(t *testing.T) {
	_ = PreloadCount.User

	// Verify UserGroups preloader exists and returns a Preloader
	_ = PreloadCount.User.UserGroups()
}

// Test that User has PreloadCount method
func TestUserPreloadCountMethod(t *testing.T) {
	var m *User

	_ = m.PreloadCount("UserGroups", 0)
}
