// Code generated by BobGen sql v0.49.0. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package dberror

var GroupErrors = &groupErrors{
	ErrUniqueGroupsPkey: &UniqueConstraintError{
		schema:  "",
		table:   "groups",
		columns: []string{"id"},
		s:       "groups_pkey",
	},

	ErrUniqueGroupsNameKey: &UniqueConstraintError{
		schema:  "",
		table:   "groups",
		columns: []string{"name"},
		s:       "groups_name_key",
	},
}

type groupErrors struct {
	ErrUniqueGroupsPkey *UniqueConstraintError

	ErrUniqueGroupsNameKey *UniqueConstraintError
}
