// Code generated by BobGen sql v0.49.0. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package dberror

var UserErrors = &userErrors{
	ErrUniqueUsersPkey: &UniqueConstraintError{
		schema:  "",
		table:   "users",
		columns: []string{"id"},
		s:       "users_pkey",
	},

	ErrUniqueUsersEmailKey: &UniqueConstraintError{
		schema:  "",
		table:   "users",
		columns: []string{"email"},
		s:       "users_email_key",
	},

	ErrUniqueUsersUsernameKey: &UniqueConstraintError{
		schema:  "",
		table:   "users",
		columns: []string{"username"},
		s:       "users_username_key",
	},
}

type userErrors struct {
	ErrUniqueUsersPkey *UniqueConstraintError

	ErrUniqueUsersEmailKey *UniqueConstraintError

	ErrUniqueUsersUsernameKey *UniqueConstraintError
}
