// Code generated by BobGen sql v0.49.0. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package dberror

var UserGroupErrors = &userGroupErrors{
	ErrUniqueUserGroupsPkey: &UniqueConstraintError{
		schema:  "",
		table:   "user_groups",
		columns: []string{"user_id", "group_id"},
		s:       "user_groups_pkey",
	},
}

type userGroupErrors struct {
	ErrUniqueUserGroupsPkey *UniqueConstraintError
}
