// Code generated by BobGen sql v0.50.0. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package dberror

import (
	"errors"
	"testing"

	"github.com/jackc/pgx/v5/pgconn"
)

func TestCheckConstraintErrors(t *testing.T) {
	newCheckErr := func(code, constraintName string) error {
		return &pgconn.PgError{Code: code, ConstraintName: constraintName}
	}

	checkErr := newCheckErr("23514", "some_constraint")
	if !errors.Is(ErrCheckConstraint, checkErr) {
		t.Fatal("expected ErrCheckConstraint to match check violation")
	}
	if !ErrCheckConstraint.Is(checkErr) {
		t.Fatal("expected ErrCheckConstraint.Is to match check violation")
	}

	uniqueErr := newCheckErr("23505", "some_constraint")
	if errors.Is(ErrCheckConstraint, uniqueErr) {
		t.Fatal("expected ErrCheckConstraint not to match unique violation")
	}
	if ErrCheckConstraint.Is(uniqueErr) {
		t.Fatal("expected ErrCheckConstraint.Is not to match unique violation")
	}

	t.Run("Transaction_ErrCheckTransactionsAmountCheck", func(t *testing.T) {
		matchingErr := newCheckErr("23514", "transactions_amount_check")
		if !errors.Is(TransactionErrors.ErrCheckTransactionsAmountCheck, matchingErr) {
			t.Fatalf("expected ErrCheckTransactionsAmountCheck to match constraint %q", "transactions_amount_check")
		}
		if !TransactionErrors.ErrCheckTransactionsAmountCheck.Is(matchingErr) {
			t.Fatalf("expected ErrCheckTransactionsAmountCheck.Is to match constraint %q", "transactions_amount_check")
		}

		nonMatchingErr := newCheckErr("23514", "other_constraint")
		if errors.Is(TransactionErrors.ErrCheckTransactionsAmountCheck, nonMatchingErr) {
			t.Fatal("expected ErrCheckTransactionsAmountCheck not to match different constraint")
		}
		if TransactionErrors.ErrCheckTransactionsAmountCheck.Is(nonMatchingErr) {
			t.Fatal("expected ErrCheckTransactionsAmountCheck.Is not to match different constraint")
		}
	})
	t.Run("Transaction_ErrCheckTransactionsCategoryCheck", func(t *testing.T) {
		matchingErr := newCheckErr("23514", "transactions_category_check")
		if !errors.Is(TransactionErrors.ErrCheckTransactionsCategoryCheck, matchingErr) {
			t.Fatalf("expected ErrCheckTransactionsCategoryCheck to match constraint %q", "transactions_category_check")
		}
		if !TransactionErrors.ErrCheckTransactionsCategoryCheck.Is(matchingErr) {
			t.Fatalf("expected ErrCheckTransactionsCategoryCheck.Is to match constraint %q", "transactions_category_check")
		}

		nonMatchingErr := newCheckErr("23514", "other_constraint")
		if errors.Is(TransactionErrors.ErrCheckTransactionsCategoryCheck, nonMatchingErr) {
			t.Fatal("expected ErrCheckTransactionsCategoryCheck not to match different constraint")
		}
		if TransactionErrors.ErrCheckTransactionsCategoryCheck.Is(nonMatchingErr) {
			t.Fatal("expected ErrCheckTransactionsCategoryCheck.Is not to match different constraint")
		}
	})
	t.Run("Transaction_ErrCheckTransactionsOwnerCheck", func(t *testing.T) {
		matchingErr := newCheckErr("23514", "transactions_owner_check")
		if !errors.Is(TransactionErrors.ErrCheckTransactionsOwnerCheck, matchingErr) {
			t.Fatalf("expected ErrCheckTransactionsOwnerCheck to match constraint %q", "transactions_owner_check")
		}
		if !TransactionErrors.ErrCheckTransactionsOwnerCheck.Is(matchingErr) {
			t.Fatalf("expected ErrCheckTransactionsOwnerCheck.Is to match constraint %q", "transactions_owner_check")
		}

		nonMatchingErr := newCheckErr("23514", "other_constraint")
		if errors.Is(TransactionErrors.ErrCheckTransactionsOwnerCheck, nonMatchingErr) {
			t.Fatal("expected ErrCheckTransactionsOwnerCheck not to match different constraint")
		}
		if TransactionErrors.ErrCheckTransactionsOwnerCheck.Is(nonMatchingErr) {
			t.Fatal("expected ErrCheckTransactionsOwnerCheck.Is not to match different constraint")
		}
	})
	t.Run("Transaction_ErrCheckTransactionsTypeCheck", func(t *testing.T) {
		matchingErr := newCheckErr("23514", "transactions_type_check")
		if !errors.Is(TransactionErrors.ErrCheckTransactionsTypeCheck, matchingErr) {
			t.Fatalf("expected ErrCheckTransactionsTypeCheck to match constraint %q", "transactions_type_check")
		}
		if !TransactionErrors.ErrCheckTransactionsTypeCheck.Is(matchingErr) {
			t.Fatalf("expected ErrCheckTransactionsTypeCheck.Is to match constraint %q", "transactions_type_check")
		}

		nonMatchingErr := newCheckErr("23514", "other_constraint")
		if errors.Is(TransactionErrors.ErrCheckTransactionsTypeCheck, nonMatchingErr) {
			t.Fatal("expected ErrCheckTransactionsTypeCheck not to match different constraint")
		}
		if TransactionErrors.ErrCheckTransactionsTypeCheck.Is(nonMatchingErr) {
			t.Fatal("expected ErrCheckTransactionsTypeCheck.Is not to match different constraint")
		}
	})
}
