// Code generated by BobGen sql v0.50.0. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package dberror

var TransactionErrors = &transactionErrors{
	ErrUniqueTransactionsPkey: &UniqueConstraintError{
		schema:  "",
		table:   "transactions",
		columns: []string{"id"},
		s:       "transactions_pkey",
	},

	ErrCheckTransactionsAmountCheck: &CheckConstraintError{
		schema:  "",
		table:   "transactions",
		columns: []string{"amount"},
		s:       "transactions_amount_check",
	},

	ErrCheckTransactionsCategoryCheck: &CheckConstraintError{
		schema:  "",
		table:   "transactions",
		columns: []string{"category"},
		s:       "transactions_category_check",
	},

	ErrCheckTransactionsOwnerCheck: &CheckConstraintError{
		schema:  "",
		table:   "transactions",
		columns: []string{"owner"},
		s:       "transactions_owner_check",
	},

	ErrCheckTransactionsTypeCheck: &CheckConstraintError{
		schema:  "",
		table:   "transactions",
		columns: []string{"type"},
		s:       "transactions_type_check",
	},
}

type transactionErrors struct {
	ErrUniqueTransactionsPkey *UniqueConstraintError

	ErrCheckTransactionsAmountCheck *CheckConstraintError

	ErrCheckTransactionsCategoryCheck *CheckConstraintError

	ErrCheckTransactionsOwnerCheck *CheckConstraintError

	ErrCheckTransactionsTypeCheck *CheckConstraintError
}
