// Code generated by BobGen sql v0.49.0. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package dbinfo

import "github.com/aarondl/opt/null"

var Groups = Table[
	groupColumns,
	groupIndexes,
	groupForeignKeys,
	groupUniques,
	groupChecks,
]{
	Schema: "",
	Name:   "groups",
	Columns: groupColumns{
		ID: column{
			Name:      "id",
			DBType:    "uuid",
			Default:   "",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		Name: column{
			Name:      "name",
			DBType:    "character varying",
			Default:   "",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		Description: column{
			Name:      "description",
			DBType:    "text",
			Default:   "NULL",
			Comment:   "",
			Nullable:  true,
			Generated: false,
			AutoIncr:  false,
		},
		CreatedAt: column{
			Name:      "created_at",
			DBType:    "timestamp with time zone",
			Default:   "now()",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		UpdatedAt: column{
			Name:      "updated_at",
			DBType:    "timestamp with time zone",
			Default:   "now()",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		GroupInfo: column{
			Name:      "group_info",
			DBType:    "jsonb",
			Default:   "NULL",
			Comment:   "",
			Nullable:  true,
			Generated: false,
			AutoIncr:  false,
		},
	},
	Indexes: groupIndexes{
		GroupsPkey: index{
			Type: "btree",
			Name: "groups_pkey",
			Columns: []indexColumn{
				{
					Name:         "id",
					Desc:         null.FromCond(false, true),
					IsExpression: false,
				},
			},
			Unique:        true,
			Comment:       "",
			NullsFirst:    []bool{false},
			NullsDistinct: false,
			Where:         "",
			Include:       []string{},
		},
		GroupsNameKey: index{
			Type: "btree",
			Name: "groups_name_key",
			Columns: []indexColumn{
				{
					Name:         "name",
					Desc:         null.FromCond(false, true),
					IsExpression: false,
				},
			},
			Unique:        true,
			Comment:       "",
			NullsFirst:    []bool{false},
			NullsDistinct: false,
			Where:         "",
			Include:       []string{},
		},
		IdxGroupsCreatedAt: index{
			Type: "btree",
			Name: "idx_groups_created_at",
			Columns: []indexColumn{
				{
					Name:         "created_at",
					Desc:         null.FromCond(false, true),
					IsExpression: false,
				},
			},
			Unique:        false,
			Comment:       "",
			NullsFirst:    []bool{false},
			NullsDistinct: false,
			Where:         "",
			Include:       []string{},
		},
	},
	PrimaryKey: &constraint{
		Name:    "groups_pkey",
		Columns: []string{"id"},
		Comment: "",
	},

	Uniques: groupUniques{
		GroupsNameKey: constraint{
			Name:    "groups_name_key",
			Columns: []string{"name"},
			Comment: "",
		},
	},

	Comment: "",
}

type groupColumns struct {
	ID          column
	Name        column
	Description column
	CreatedAt   column
	UpdatedAt   column
	GroupInfo   column
}

func (c groupColumns) AsSlice() []column {
	return []column{
		c.ID, c.Name, c.Description, c.CreatedAt, c.UpdatedAt, c.GroupInfo,
	}
}

type groupIndexes struct {
	GroupsPkey         index
	GroupsNameKey      index
	IdxGroupsCreatedAt index
}

func (i groupIndexes) AsSlice() []index {
	return []index{
		i.GroupsPkey, i.GroupsNameKey, i.IdxGroupsCreatedAt,
	}
}

type groupForeignKeys struct{}

func (f groupForeignKeys) AsSlice() []foreignKey {
	return []foreignKey{}
}

type groupUniques struct {
	GroupsNameKey constraint
}

func (u groupUniques) AsSlice() []constraint {
	return []constraint{
		u.GroupsNameKey,
	}
}

type groupChecks struct{}

func (c groupChecks) AsSlice() []check {
	return []check{}
}
