// Code generated by BobGen sql v0.49.0. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package dbinfo

import "github.com/aarondl/opt/null"

var UserGroups = Table[
	userGroupColumns,
	userGroupIndexes,
	userGroupForeignKeys,
	userGroupUniques,
	userGroupChecks,
]{
	Schema: "",
	Name:   "user_groups",
	Columns: userGroupColumns{
		UserID: column{
			Name:      "user_id",
			DBType:    "uuid",
			Default:   "",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		GroupID: column{
			Name:      "group_id",
			DBType:    "uuid",
			Default:   "",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		JoinedAt: column{
			Name:      "joined_at",
			DBType:    "timestamp with time zone",
			Default:   "now()",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
	},
	Indexes: userGroupIndexes{
		UserGroupsPkey: index{
			Type: "btree",
			Name: "user_groups_pkey",
			Columns: []indexColumn{
				{
					Name:         "user_id",
					Desc:         null.FromCond(false, true),
					IsExpression: false,
				},
				{
					Name:         "group_id",
					Desc:         null.FromCond(false, true),
					IsExpression: false,
				},
			},
			Unique:        true,
			Comment:       "",
			NullsFirst:    []bool{false, false},
			NullsDistinct: false,
			Where:         "",
			Include:       []string{},
		},
		IdxUserGroupsGroupID: index{
			Type: "btree",
			Name: "idx_user_groups_group_id",
			Columns: []indexColumn{
				{
					Name:         "group_id",
					Desc:         null.FromCond(false, true),
					IsExpression: false,
				},
			},
			Unique:        false,
			Comment:       "",
			NullsFirst:    []bool{false},
			NullsDistinct: false,
			Where:         "",
			Include:       []string{},
		},
	},
	PrimaryKey: &constraint{
		Name:    "user_groups_pkey",
		Columns: []string{"user_id", "group_id"},
		Comment: "",
	},
	ForeignKeys: userGroupForeignKeys{
		UserGroupsUserGroupsGroupIDFkey: foreignKey{
			constraint: constraint{
				Name:    "user_groups.user_groups_group_id_fkey",
				Columns: []string{"group_id"},
				Comment: "",
			},
			ForeignTable:   "groups",
			ForeignColumns: []string{"id"},
		},
		UserGroupsUserGroupsUserIDFkey: foreignKey{
			constraint: constraint{
				Name:    "user_groups.user_groups_user_id_fkey",
				Columns: []string{"user_id"},
				Comment: "",
			},
			ForeignTable:   "users",
			ForeignColumns: []string{"id"},
		},
	},

	Comment: "",
}

type userGroupColumns struct {
	UserID   column
	GroupID  column
	JoinedAt column
}

func (c userGroupColumns) AsSlice() []column {
	return []column{
		c.UserID, c.GroupID, c.JoinedAt,
	}
}

type userGroupIndexes struct {
	UserGroupsPkey       index
	IdxUserGroupsGroupID index
}

func (i userGroupIndexes) AsSlice() []index {
	return []index{
		i.UserGroupsPkey, i.IdxUserGroupsGroupID,
	}
}

type userGroupForeignKeys struct {
	UserGroupsUserGroupsGroupIDFkey foreignKey
	UserGroupsUserGroupsUserIDFkey  foreignKey
}

func (f userGroupForeignKeys) AsSlice() []foreignKey {
	return []foreignKey{
		f.UserGroupsUserGroupsGroupIDFkey, f.UserGroupsUserGroupsUserIDFkey,
	}
}

type userGroupUniques struct{}

func (u userGroupUniques) AsSlice() []constraint {
	return []constraint{}
}

type userGroupChecks struct{}

func (c userGroupChecks) AsSlice() []check {
	return []check{}
}
