// Code generated by BobGen sql v0.49.0. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package dbinfo

import "github.com/aarondl/opt/null"

var Users = Table[
	userColumns,
	userIndexes,
	userForeignKeys,
	userUniques,
	userChecks,
]{
	Schema: "",
	Name:   "users",
	Columns: userColumns{
		ID: column{
			Name:      "id",
			DBType:    "uuid",
			Default:   "",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		Username: column{
			Name:      "username",
			DBType:    "character varying",
			Default:   "",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		Email: column{
			Name:      "email",
			DBType:    "character varying",
			Default:   "",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		FirstName: column{
			Name:      "first_name",
			DBType:    "character varying",
			Default:   "",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		LastName: column{
			Name:      "last_name",
			DBType:    "character varying",
			Default:   "",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		CreatedAt: column{
			Name:      "created_at",
			DBType:    "timestamp with time zone",
			Default:   "now()",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		UpdatedAt: column{
			Name:      "updated_at",
			DBType:    "timestamp with time zone",
			Default:   "now()",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
	},
	Indexes: userIndexes{
		UsersPkey: index{
			Type: "btree",
			Name: "users_pkey",
			Columns: []indexColumn{
				{
					Name:         "id",
					Desc:         null.FromCond(false, true),
					IsExpression: false,
				},
			},
			Unique:        true,
			Comment:       "",
			NullsFirst:    []bool{false},
			NullsDistinct: false,
			Where:         "",
			Include:       []string{},
		},
		IdxUsersCreatedAt: index{
			Type: "btree",
			Name: "idx_users_created_at",
			Columns: []indexColumn{
				{
					Name:         "created_at",
					Desc:         null.FromCond(false, true),
					IsExpression: false,
				},
			},
			Unique:        false,
			Comment:       "",
			NullsFirst:    []bool{false},
			NullsDistinct: false,
			Where:         "",
			Include:       []string{},
		},
		UsersEmailKey: index{
			Type: "btree",
			Name: "users_email_key",
			Columns: []indexColumn{
				{
					Name:         "email",
					Desc:         null.FromCond(false, true),
					IsExpression: false,
				},
			},
			Unique:        true,
			Comment:       "",
			NullsFirst:    []bool{false},
			NullsDistinct: false,
			Where:         "",
			Include:       []string{},
		},
		UsersUsernameKey: index{
			Type: "btree",
			Name: "users_username_key",
			Columns: []indexColumn{
				{
					Name:         "username",
					Desc:         null.FromCond(false, true),
					IsExpression: false,
				},
			},
			Unique:        true,
			Comment:       "",
			NullsFirst:    []bool{false},
			NullsDistinct: false,
			Where:         "",
			Include:       []string{},
		},
	},
	PrimaryKey: &constraint{
		Name:    "users_pkey",
		Columns: []string{"id"},
		Comment: "",
	},

	Uniques: userUniques{
		UsersEmailKey: constraint{
			Name:    "users_email_key",
			Columns: []string{"email"},
			Comment: "",
		},
		UsersUsernameKey: constraint{
			Name:    "users_username_key",
			Columns: []string{"username"},
			Comment: "",
		},
	},

	Comment: "",
}

type userColumns struct {
	ID        column
	Username  column
	Email     column
	FirstName column
	LastName  column
	CreatedAt column
	UpdatedAt column
}

func (c userColumns) AsSlice() []column {
	return []column{
		c.ID, c.Username, c.Email, c.FirstName, c.LastName, c.CreatedAt, c.UpdatedAt,
	}
}

type userIndexes struct {
	UsersPkey         index
	IdxUsersCreatedAt index
	UsersEmailKey     index
	UsersUsernameKey  index
}

func (i userIndexes) AsSlice() []index {
	return []index{
		i.UsersPkey, i.IdxUsersCreatedAt, i.UsersEmailKey, i.UsersUsernameKey,
	}
}

type userForeignKeys struct{}

func (f userForeignKeys) AsSlice() []foreignKey {
	return []foreignKey{}
}

type userUniques struct {
	UsersEmailKey    constraint
	UsersUsernameKey constraint
}

func (u userUniques) AsSlice() []constraint {
	return []constraint{
		u.UsersEmailKey, u.UsersUsernameKey,
	}
}

type userChecks struct{}

func (c userChecks) AsSlice() []check {
	return []check{}
}
