// Code generated by BobGen sql v0.49.0. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package model

import (
	"github.com/stephenafamo/bob/clause"
	"github.com/stephenafamo/bob/dialect/psql"
	"github.com/stephenafamo/bob/dialect/psql/dialect"
)

var (
	SelectWhere     = Where[*dialect.SelectQuery]()
	UpdateWhere     = Where[*dialect.UpdateQuery]()
	DeleteWhere     = Where[*dialect.DeleteQuery]()
	OnConflictWhere = Where[*clause.ConflictClause]() // Used in ON CONFLICT DO UPDATE
)

func Where[Q psql.Filterable]() struct {
	Groups     groupWhere[Q]
	UserGroups userGroupWhere[Q]
	Users      userWhere[Q]
} {
	return struct {
		Groups     groupWhere[Q]
		UserGroups userGroupWhere[Q]
		Users      userWhere[Q]
	}{
		Groups:     buildGroupWhere[Q](Groups.Columns),
		UserGroups: buildUserGroupWhere[Q](UserGroups.Columns),
		Users:      buildUserWhere[Q](Users.Columns),
	}
}
