// Code generated by BobGen sql v0.49.0. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package model

import (
	"context"
	"strings"
	"testing"

	"github.com/stephenafamo/bob"
	"github.com/stephenafamo/bob/dialect/psql"
	"github.com/stephenafamo/bob/dialect/psql/sm"
)

// TestGroupHasRelationsEmitExists verifies that every generated
// Has{Rel} helper produces a correlated EXISTS subquery (semi-join) rather than
// an INNER JOIN, so the parent rows are never multiplied.
func TestGroupHasRelationsEmitExists(t *testing.T) {
	ctx := context.Background()

	t.Run("UserGroups", func(t *testing.T) {
		q := psql.Select(
			sm.From(Groups.NameExpr()),
			SelectWhere.Groups.R.HasUserGroups(),
		)
		sql, _, err := bob.Build(ctx, q)
		if err != nil {
			t.Fatalf("HasUserGroups: build error: %v", err)
		}
		if !strings.Contains(sql, "EXISTS") {
			t.Errorf("HasUserGroups: expected EXISTS in query, got: %s", sql)
		}
	})
}

// TestUserGroupHasRelationsEmitExists verifies that every generated
// Has{Rel} helper produces a correlated EXISTS subquery (semi-join) rather than
// an INNER JOIN, so the parent rows are never multiplied.
func TestUserGroupHasRelationsEmitExists(t *testing.T) {
	ctx := context.Background()

	t.Run("Group", func(t *testing.T) {
		q := psql.Select(
			sm.From(UserGroups.NameExpr()),
			SelectWhere.UserGroups.R.HasGroup(),
		)
		sql, _, err := bob.Build(ctx, q)
		if err != nil {
			t.Fatalf("HasGroup: build error: %v", err)
		}
		if !strings.Contains(sql, "EXISTS") {
			t.Errorf("HasGroup: expected EXISTS in query, got: %s", sql)
		}
	})

	t.Run("User", func(t *testing.T) {
		q := psql.Select(
			sm.From(UserGroups.NameExpr()),
			SelectWhere.UserGroups.R.HasUser(),
		)
		sql, _, err := bob.Build(ctx, q)
		if err != nil {
			t.Fatalf("HasUser: build error: %v", err)
		}
		if !strings.Contains(sql, "EXISTS") {
			t.Errorf("HasUser: expected EXISTS in query, got: %s", sql)
		}
	})
}

// TestUserHasRelationsEmitExists verifies that every generated
// Has{Rel} helper produces a correlated EXISTS subquery (semi-join) rather than
// an INNER JOIN, so the parent rows are never multiplied.
func TestUserHasRelationsEmitExists(t *testing.T) {
	ctx := context.Background()

	t.Run("UserGroups", func(t *testing.T) {
		q := psql.Select(
			sm.From(Users.NameExpr()),
			SelectWhere.Users.R.HasUserGroups(),
		)
		sql, _, err := bob.Build(ctx, q)
		if err != nil {
			t.Fatalf("HasUserGroups: build error: %v", err)
		}
		if !strings.Contains(sql, "EXISTS") {
			t.Errorf("HasUserGroups: expected EXISTS in query, got: %s", sql)
		}
	})
}
