// Code generated by BobGen sql v0.49.0. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package model

import (
	"database/sql"
	"database/sql/driver"

	"github.com/manhrev/gorest/internal/dto"
	"github.com/stephenafamo/bob"
	"github.com/stephenafamo/bob/types"
)

// Set the testDB to enable tests that use the database
var testDB bob.Transactor[bob.Tx]

// Make sure the type Group runs hooks after queries
var _ bob.HookableType = &Group{}

// Make sure the type UserGroup runs hooks after queries
var _ bob.HookableType = &UserGroup{}

// Make sure the type User runs hooks after queries
var _ bob.HookableType = &User{}

// Make sure the type types.JSON[dto.UserMetaBox] satisfies database/sql.Scanner
var _ sql.Scanner = (*types.JSON[dto.UserMetaBox])(nil)

// Make sure the type types.JSON[dto.UserMetaBox] satisfies database/sql/driver.Valuer
var _ driver.Valuer = *new(types.JSON[dto.UserMetaBox])
