// Code generated by BobGen sql v0.49.0. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package model

import "github.com/stephenafamo/bob"

// Set the testDB to enable tests that use the database
var testDB bob.Transactor[bob.Tx]

// Make sure the type Group runs hooks after queries
var _ bob.HookableType = &Group{}

// Make sure the type UserGroup runs hooks after queries
var _ bob.HookableType = &UserGroup{}

// Make sure the type User runs hooks after queries
var _ bob.HookableType = &User{}
