// Code generated by BobGen sql v0.49.0. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package model

import (
	"context"
	"database/sql"
	"fmt"
	"io"
	"strings"
	"time"

	"github.com/manhrev/gorest/internal/dto"
	"github.com/stephenafamo/bob"
	"github.com/stephenafamo/bob/dialect/psql"
	"github.com/stephenafamo/bob/dialect/psql/dialect"
	"github.com/stephenafamo/bob/dialect/psql/dm"
	"github.com/stephenafamo/bob/dialect/psql/sm"
	"github.com/stephenafamo/bob/dialect/psql/um"
	"github.com/stephenafamo/bob/expr"
	"github.com/stephenafamo/bob/mods"
	"github.com/stephenafamo/bob/orm"
	"github.com/stephenafamo/bob/types"
	"github.com/stephenafamo/bob/types/pgtypes"
	"github.com/stephenafamo/scan"
)

// Group is an object representing the database table.
type Group struct {
	ID          string                                 `db:"id,pk" `
	Name        string                                 `db:"name" `
	Description sql.Null[string]                       `db:"description" `
	CreatedAt   time.Time                              `db:"created_at" `
	UpdatedAt   time.Time                              `db:"updated_at" `
	GroupInfo   sql.Null[types.JSON[dto.GroupInfoBox]] `db:"group_info" `

	R groupR `db:"-" `

	C groupC `db:"-" `
}

// GroupSlice is an alias for a slice of pointers to Group.
// This should almost always be used instead of []*Group.
type GroupSlice []*Group

// Groups contains methods to work with the groups table
var Groups = psql.NewTablex[*Group, GroupSlice, *GroupSetter]("", "groups", buildGroupColumns("groups"), groupScanMapper)

// GroupsQuery is a query on the groups table
type GroupsQuery = *psql.ViewQuery[*Group, GroupSlice]

// groupR is where relationships are stored.
type groupR struct {
	UserGroups UserGroupSlice // user_groups.user_groups_group_id_fkey
	// Loaded reports whether each relationship has been loaded.
	// A relationship's bool is set by Load*, Preload, ThenLoad, factory builds,
	// and to-one Attach/Insert operations. To-many Attach/Insert operations leave it unchanged.
	Loaded groupRLoaded `db:"-" `
}

// groupRLoaded tracks which relationships on Group have been loaded.
type groupRLoaded struct {
	UserGroups bool // user_groups.user_groups_group_id_fkey
}

func buildGroupColumns(tableName string) groupColumns {
	columnsExpr := expr.NewColumnsExpr(
		"id", "name", "description", "created_at", "updated_at", "group_info",
	)

	if tableName != "" {
		columnsExpr = columnsExpr.WithParent(tableName)
	}

	return groupColumns{
		ColumnsExpr: columnsExpr,
		tableAlias:  tableName,
		ID:          buildGroupColumn(tableName, "id"),
		Name:        buildGroupColumn(tableName, "name"),
		Description: buildGroupColumn(tableName, "description"),
		CreatedAt:   buildGroupColumn(tableName, "created_at"),
		UpdatedAt:   buildGroupColumn(tableName, "updated_at"),
		GroupInfo:   buildGroupColumn(tableName, "group_info"),
	}
}

type groupColumns struct {
	expr.ColumnsExpr
	tableAlias  string
	ID          groupColumn
	Name        groupColumn
	Description groupColumn
	CreatedAt   groupColumn
	UpdatedAt   groupColumn
	GroupInfo   groupColumn
}

// Alias returns the current table alias for the columns set.
func (c groupColumns) Alias() string {
	return c.tableAlias
}

// AliasedAs returns a copy of the columns set qualified by tableName.
func (groupColumns) AliasedAs(tableName string) groupColumns {
	return buildGroupColumns(tableName)
}

// Unqualified returns a copy of the columns set without table qualification.
func (c groupColumns) Unqualified() groupColumns {
	return buildGroupColumns("")
}

func buildGroupColumn(alias, name string) groupColumn {
	return groupColumn{
		Expression: psql.Quote(alias, name),
		alias:      alias,
		name:       name,
	}
}

type groupColumn struct {
	psql.Expression
	alias string
	name  string
}

// Name returns the unqualified column name.
func (c groupColumn) Name() string {
	return c.name
}

// ShouldOmitParens prevents automatic parenthesis wrapping in expression builders.
func (c groupColumn) ShouldOmitParens() bool {
	return true
}

// GroupSetter is used for insert/upsert/update operations
// All values are optional, and do not have to be set
// Generated columns are not included
type GroupSetter struct {
	ID          *string                                 `db:"id,pk" `
	Name        *string                                 `db:"name" `
	Description *sql.Null[string]                       `db:"description" `
	CreatedAt   *time.Time                              `db:"created_at" `
	UpdatedAt   *time.Time                              `db:"updated_at" `
	GroupInfo   *sql.Null[types.JSON[dto.GroupInfoBox]] `db:"group_info" `
}

func (s GroupSetter) SetColumns() []string {
	vals := make([]string, 0, 6)
	if s.ID != nil {
		vals = append(vals, "id")
	}
	if s.Name != nil {
		vals = append(vals, "name")
	}
	if s.Description != nil {
		vals = append(vals, "description")
	}
	if s.CreatedAt != nil {
		vals = append(vals, "created_at")
	}
	if s.UpdatedAt != nil {
		vals = append(vals, "updated_at")
	}
	if s.GroupInfo != nil {
		vals = append(vals, "group_info")
	}
	return vals
}

func (s GroupSetter) Overwrite(t *Group) {
	if s.ID != nil {
		t.ID = func() string {
			if s.ID == nil {
				return *new(string)
			}
			return *s.ID
		}()
	}
	if s.Name != nil {
		t.Name = func() string {
			if s.Name == nil {
				return *new(string)
			}
			return *s.Name
		}()
	}
	if s.Description != nil {
		t.Description = func() sql.Null[string] {
			if s.Description == nil {
				return *new(sql.Null[string])
			}
			v := s.Description
			return *v
		}()
	}
	if s.CreatedAt != nil {
		t.CreatedAt = func() time.Time {
			if s.CreatedAt == nil {
				return *new(time.Time)
			}
			return *s.CreatedAt
		}()
	}
	if s.UpdatedAt != nil {
		t.UpdatedAt = func() time.Time {
			if s.UpdatedAt == nil {
				return *new(time.Time)
			}
			return *s.UpdatedAt
		}()
	}
	if s.GroupInfo != nil {
		t.GroupInfo = func() sql.Null[types.JSON[dto.GroupInfoBox]] {
			if s.GroupInfo == nil {
				return *new(sql.Null[types.JSON[dto.GroupInfoBox]])
			}
			v := s.GroupInfo
			return *v
		}()
	}
}

func (s *GroupSetter) Apply(q *dialect.InsertQuery) {
	q.AppendHooks(func(ctx context.Context, exec bob.Executor) (context.Context, error) {
		return Groups.BeforeInsertHooks.RunHooks(ctx, exec, s)
	})

	q.AppendValues(
		bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
			if s.ID == nil {
				return psql.Raw("DEFAULT").WriteSQL(ctx, w, d, start)
			}
			return psql.Arg(func() string {
				if s.ID == nil {
					return *new(string)
				}
				return *s.ID
			}()).WriteSQL(ctx, w, d, start)
		}), bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
			if s.Name == nil {
				return psql.Raw("DEFAULT").WriteSQL(ctx, w, d, start)
			}
			return psql.Arg(func() string {
				if s.Name == nil {
					return *new(string)
				}
				return *s.Name
			}()).WriteSQL(ctx, w, d, start)
		}), bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
			if s.Description == nil {
				return psql.Raw("DEFAULT").WriteSQL(ctx, w, d, start)
			}
			return psql.Arg(func() sql.Null[string] {
				if s.Description == nil {
					return *new(sql.Null[string])
				}
				v := s.Description
				return *v
			}()).WriteSQL(ctx, w, d, start)
		}), bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
			if s.CreatedAt == nil {
				return psql.Raw("DEFAULT").WriteSQL(ctx, w, d, start)
			}
			return psql.Arg(func() time.Time {
				if s.CreatedAt == nil {
					return *new(time.Time)
				}
				return *s.CreatedAt
			}()).WriteSQL(ctx, w, d, start)
		}), bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
			if s.UpdatedAt == nil {
				return psql.Raw("DEFAULT").WriteSQL(ctx, w, d, start)
			}
			return psql.Arg(func() time.Time {
				if s.UpdatedAt == nil {
					return *new(time.Time)
				}
				return *s.UpdatedAt
			}()).WriteSQL(ctx, w, d, start)
		}), bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
			if s.GroupInfo == nil {
				return psql.Raw("DEFAULT").WriteSQL(ctx, w, d, start)
			}
			return psql.Arg(func() sql.Null[types.JSON[dto.GroupInfoBox]] {
				if s.GroupInfo == nil {
					return *new(sql.Null[types.JSON[dto.GroupInfoBox]])
				}
				v := s.GroupInfo
				return *v
			}()).WriteSQL(ctx, w, d, start)
		}))
}

func (s GroupSetter) UpdateMod() bob.Mod[*dialect.UpdateQuery] {
	return um.Set(s.Expressions()...)
}

func (s GroupSetter) Expressions(prefix ...string) []bob.Expression {
	exprs := make([]bob.Expression, 0, 6)

	if s.ID != nil {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "id")...),
			psql.Arg(s.ID),
		}})
	}

	if s.Name != nil {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "name")...),
			psql.Arg(s.Name),
		}})
	}

	if s.Description != nil {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "description")...),
			psql.Arg(s.Description),
		}})
	}

	if s.CreatedAt != nil {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "created_at")...),
			psql.Arg(s.CreatedAt),
		}})
	}

	if s.UpdatedAt != nil {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "updated_at")...),
			psql.Arg(s.UpdatedAt),
		}})
	}

	if s.GroupInfo != nil {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "group_info")...),
			psql.Arg(s.GroupInfo),
		}})
	}

	return exprs
}

// scan.Mapper[*T] without reflection: maps columns to fields by index.
func groupScanMapper(ctx context.Context, cols []string) (scan.BeforeFunc, func(any) (*Group, error)) {
	// resolve the column positions once per query, not per row
	type target struct {
		idx int
		dst func(o *Group) any
	}
	targets := make([]target, 0, 6)
	for i, col := range cols {
		switch col {
		case "id":
			targets = append(targets, target{i, func(o *Group) any { return &o.ID }})
		case "name":
			targets = append(targets, target{i, func(o *Group) any { return &o.Name }})
		case "description":
			targets = append(targets, target{i, func(o *Group) any { return &o.Description }})
		case "created_at":
			targets = append(targets, target{i, func(o *Group) any { return &o.CreatedAt }})
		case "updated_at":
			targets = append(targets, target{i, func(o *Group) any { return &o.UpdatedAt }})
		case "group_info":
			targets = append(targets, target{i, func(o *Group) any { return &o.GroupInfo }})
		}
	}

	return func(row *scan.Row) (any, error) {
			o := new(Group)
			for _, t := range targets {
				row.ScheduleScanByIndex(t.idx, t.dst(o))
			}
			return o, nil
		}, func(v any) (*Group, error) {
			return v.(*Group), nil
		}
}

// FindGroup retrieves a single record by primary key
// If cols is empty Find will return all columns.
func FindGroup(ctx context.Context, exec bob.Executor, IDPK string, cols ...string) (*Group, error) {
	if len(cols) == 0 {
		return Groups.Query(
			sm.Where(Groups.Columns.ID.EQ(psql.Arg(IDPK))),
		).One(ctx, exec)
	}

	return Groups.Query(
		sm.Where(Groups.Columns.ID.EQ(psql.Arg(IDPK))),
		sm.Columns(Groups.Columns.Only(cols...)),
	).One(ctx, exec)
}

// GroupExists checks the presence of a single record by primary key
func GroupExists(ctx context.Context, exec bob.Executor, IDPK string) (bool, error) {
	return Groups.Query(
		sm.Where(Groups.Columns.ID.EQ(psql.Arg(IDPK))),
	).Exists(ctx, exec)
}

// AfterQueryHook is called after Group is retrieved from the database
func (o *Group) AfterQueryHook(ctx context.Context, exec bob.Executor, queryType bob.QueryType) error {
	var err error

	switch queryType {
	case bob.QueryTypeSelect:
		ctx, err = Groups.AfterSelectHooks.RunHooks(ctx, exec, GroupSlice{o})
	case bob.QueryTypeInsert:
		ctx, err = Groups.AfterInsertHooks.RunHooks(ctx, exec, GroupSlice{o})
	case bob.QueryTypeUpdate:
		ctx, err = Groups.AfterUpdateHooks.RunHooks(ctx, exec, GroupSlice{o})
	case bob.QueryTypeDelete:
		ctx, err = Groups.AfterDeleteHooks.RunHooks(ctx, exec, GroupSlice{o})
	case bob.QueryTypeMerge:
		ctx, err = Groups.AfterMergeHooks.RunHooks(ctx, exec, GroupSlice{o})
	}

	return err
}

// primaryKeyVals returns the primary key values of the Group
func (o *Group) primaryKeyVals() bob.Expression {
	return psql.Arg(o.ID)
}

func (o *Group) pkEQ() dialect.Expression {
	return psql.Quote("groups", "id").EQ(bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
		return o.primaryKeyVals().WriteSQL(ctx, w, d, start)
	}))
}

// Update uses an executor to update the Group
func (o *Group) Update(ctx context.Context, exec bob.Executor, s *GroupSetter) error {
	v, err := Groups.Update(s.UpdateMod(), um.Where(o.pkEQ())).One(ctx, exec)
	if err != nil {
		return err
	}

	o.R = v.R
	*o = *v

	return nil
}

// Delete deletes a single Group record with an executor
func (o *Group) Delete(ctx context.Context, exec bob.Executor) error {
	_, err := Groups.Delete(dm.Where(o.pkEQ())).Exec(ctx, exec)
	return err
}

// Reload refreshes the Group using the executor
func (o *Group) Reload(ctx context.Context, exec bob.Executor) error {
	o2, err := Groups.Query(
		sm.Where(Groups.Columns.ID.EQ(psql.Arg(o.ID))),
	).One(ctx, exec)
	if err != nil {
		return err
	}
	o2.R = o.R
	*o = *o2

	return nil
}

// AfterQueryHook is called after GroupSlice is retrieved from the database
func (o GroupSlice) AfterQueryHook(ctx context.Context, exec bob.Executor, queryType bob.QueryType) error {
	var err error

	switch queryType {
	case bob.QueryTypeSelect:
		ctx, err = Groups.AfterSelectHooks.RunHooks(ctx, exec, o)
	case bob.QueryTypeInsert:
		ctx, err = Groups.AfterInsertHooks.RunHooks(ctx, exec, o)
	case bob.QueryTypeUpdate:
		ctx, err = Groups.AfterUpdateHooks.RunHooks(ctx, exec, o)
	case bob.QueryTypeDelete:
		ctx, err = Groups.AfterDeleteHooks.RunHooks(ctx, exec, o)
	case bob.QueryTypeMerge:
		ctx, err = Groups.AfterMergeHooks.RunHooks(ctx, exec, o)
	}

	return err
}

func (o GroupSlice) pkIN() dialect.Expression {
	if len(o) == 0 {
		return psql.Raw("NULL")
	}

	return psql.Quote("groups", "id").In(bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
		pkPairs := make([]bob.Expression, len(o))
		for i, row := range o {
			pkPairs[i] = row.primaryKeyVals()
		}
		return bob.ExpressSlice(ctx, w, d, start, pkPairs, "", ", ", "")
	}))
}

// copyMatchingRows finds models in the given slice that have the same primary key
// then it first copies the existing relationships from the old model to the new model
// and then replaces the old model in the slice with the new model
func (o GroupSlice) copyMatchingRows(from ...*Group) {
	fromByPK := make(map[string]*Group, len(from))
	for _, new := range from {
		// keep the first row for each key, like the nested loop did
		if _, ok := fromByPK[new.ID]; !ok {
			fromByPK[new.ID] = new
		}
	}

	for i, old := range o {
		new, ok := fromByPK[old.ID]
		if !ok {
			continue
		}
		new.R = old.R
		o[i] = new
	}
}

// UpdateMod modifies an update query with "WHERE primary_key IN (o...)"
func (o GroupSlice) UpdateMod() bob.Mod[*dialect.UpdateQuery] {
	return bob.ModFunc[*dialect.UpdateQuery](func(q *dialect.UpdateQuery) {
		q.AppendHooks(func(ctx context.Context, exec bob.Executor) (context.Context, error) {
			return Groups.BeforeUpdateHooks.RunHooks(ctx, exec, o)
		})

		q.AppendLoader(bob.LoaderFunc(func(ctx context.Context, exec bob.Executor, retrieved any) error {
			var err error
			switch retrieved := retrieved.(type) {
			case *Group:
				o.copyMatchingRows(retrieved)
			case []*Group:
				o.copyMatchingRows(retrieved...)
			case GroupSlice:
				o.copyMatchingRows(retrieved...)
			default:
				// If the retrieved value is not a Group or a slice of Group
				// then run the AfterUpdateHooks on the slice
				_, err = Groups.AfterUpdateHooks.RunHooks(ctx, exec, o)
			}

			return err
		}))

		q.AppendWhere(o.pkIN())
	})
}

// DeleteMod modifies an delete query with "WHERE primary_key IN (o...)"
func (o GroupSlice) DeleteMod() bob.Mod[*dialect.DeleteQuery] {
	return bob.ModFunc[*dialect.DeleteQuery](func(q *dialect.DeleteQuery) {
		q.AppendHooks(func(ctx context.Context, exec bob.Executor) (context.Context, error) {
			return Groups.BeforeDeleteHooks.RunHooks(ctx, exec, o)
		})

		q.AppendLoader(bob.LoaderFunc(func(ctx context.Context, exec bob.Executor, retrieved any) error {
			var err error
			switch retrieved := retrieved.(type) {
			case *Group:
				o.copyMatchingRows(retrieved)
			case []*Group:
				o.copyMatchingRows(retrieved...)
			case GroupSlice:
				o.copyMatchingRows(retrieved...)
			default:
				// If the retrieved value is not a Group or a slice of Group
				// then run the AfterDeleteHooks on the slice
				_, err = Groups.AfterDeleteHooks.RunHooks(ctx, exec, o)
			}

			return err
		}))

		q.AppendWhere(o.pkIN())
	})
}

// MergeMod modifies a merge query to run BeforeMergeHooks and AfterMergeHooks
// and updates the slice with the returned rows.
func (o GroupSlice) MergeMod() bob.Mod[*dialect.MergeQuery] {
	return bob.ModFunc[*dialect.MergeQuery](func(q *dialect.MergeQuery) {
		q.AppendHooks(func(ctx context.Context, exec bob.Executor) (context.Context, error) {
			return Groups.BeforeMergeHooks.RunHooks(ctx, exec, o)
		})

		q.AppendLoader(bob.LoaderFunc(func(ctx context.Context, exec bob.Executor, retrieved any) error {
			var err error
			switch retrieved := retrieved.(type) {
			case *Group:
				o.copyMatchingRows(retrieved)
			case []*Group:
				o.copyMatchingRows(retrieved...)
			case GroupSlice:
				o.copyMatchingRows(retrieved...)
			default:
				// If the retrieved value is not a Group or a slice of Group
				// then run the AfterMergeHooks on the slice
				_, err = Groups.AfterMergeHooks.RunHooks(ctx, exec, o)
			}

			return err
		}))
	})
}

func (o GroupSlice) UpdateAll(ctx context.Context, exec bob.Executor, vals GroupSetter) error {
	if len(o) == 0 {
		return nil
	}

	_, err := Groups.Update(vals.UpdateMod(), o.UpdateMod()).All(ctx, exec)
	return err
}

func (o GroupSlice) DeleteAll(ctx context.Context, exec bob.Executor) error {
	if len(o) == 0 {
		return nil
	}

	_, err := Groups.Delete(o.DeleteMod()).Exec(ctx, exec)
	return err
}

func (o GroupSlice) ReloadAll(ctx context.Context, exec bob.Executor) error {
	if len(o) == 0 {
		return nil
	}

	o2, err := Groups.Query(sm.Where(o.pkIN())).All(ctx, exec)
	if err != nil {
		return err
	}

	o.copyMatchingRows(o2...)

	return nil
}

// UserGroups starts a query for related objects on user_groups
func (o *Group) UserGroups(mods ...bob.Mod[*dialect.SelectQuery]) UserGroupsQuery {
	return UserGroups.Query(append(mods,
		sm.Where(UserGroups.Columns.GroupID.EQ(psql.Arg(o.ID))),
	)...)
}

func (os GroupSlice) UserGroups(mods ...bob.Mod[*dialect.SelectQuery]) UserGroupsQuery {
	pkID := make(pgtypes.Array[string], 0, len(os))
	for _, o := range os {
		if o == nil {
			continue
		}
		pkID = append(pkID, o.ID)
	}

	PKArgExpr := psql.Any(psql.Cast(psql.Arg(pkID), "uuid[]"))

	return UserGroups.Query(append(mods,
		sm.Where(UserGroups.Columns.GroupID.EQ(PKArgExpr)),
	)...)
}

func insertGroupUserGroups0(ctx context.Context, exec bob.Executor, userGroups1 []*UserGroupSetter, group0 *Group) (UserGroupSlice, error) {
	for i := range userGroups1 {
		userGroups1[i].GroupID = func() *string { return &group0.ID }()
	}

	ret, err := UserGroups.Insert(bob.ToMods(userGroups1...)).All(ctx, exec)
	if err != nil {
		return ret, fmt.Errorf("insertGroupUserGroups0: %w", err)
	}

	return ret, nil
}

func attachGroupUserGroups0(ctx context.Context, exec bob.Executor, count int, userGroups1 UserGroupSlice, group0 *Group) (UserGroupSlice, error) {
	setter := &UserGroupSetter{
		GroupID: func() *string { return &group0.ID }(),
	}

	err := userGroups1.UpdateAll(ctx, exec, *setter)
	if err != nil {
		return nil, fmt.Errorf("attachGroupUserGroups0: %w", err)
	}

	return userGroups1, nil
}

func (group0 *Group) InsertUserGroups(ctx context.Context, exec bob.Executor, related ...*UserGroupSetter) error {
	if len(related) == 0 {
		return nil
	}

	var err error

	userGroups1, err := insertGroupUserGroups0(ctx, exec, related, group0)
	if err != nil {
		return err
	}

	group0.R.UserGroups = append(group0.R.UserGroups, userGroups1...)

	for _, rel := range userGroups1 {
		rel.R.Group = group0
		rel.R.Loaded.Group = true
	}
	return nil
}

func (group0 *Group) AttachUserGroups(ctx context.Context, exec bob.Executor, related ...*UserGroup) error {
	if len(related) == 0 {
		return nil
	}

	var err error
	userGroups1 := UserGroupSlice(related)

	_, err = attachGroupUserGroups0(ctx, exec, len(related), userGroups1, group0)
	if err != nil {
		return err
	}

	group0.R.UserGroups = append(group0.R.UserGroups, userGroups1...)

	for _, rel := range related {
		rel.R.Group = group0
		rel.R.Loaded.Group = true
	}

	return nil
}

type groupWhere[Q psql.Filterable] struct {
	cols        groupColumns
	ID          psql.WhereMod[Q, string]
	Name        psql.WhereMod[Q, string]
	Description psql.WhereNullMod[Q, string]
	CreatedAt   psql.WhereMod[Q, time.Time]
	UpdatedAt   psql.WhereMod[Q, time.Time]
	GroupInfo   psql.WhereNullMod[Q, types.JSON[dto.GroupInfoBox]]
	R           groupWhereR[Q]
}

func (groupWhere[Q]) AliasedAs(alias string) groupWhere[Q] {
	return buildGroupWhere[Q](buildGroupColumns(alias))
}

func buildGroupWhere[Q psql.Filterable](cols groupColumns) groupWhere[Q] {
	return groupWhere[Q]{
		cols:        cols,
		ID:          psql.Where[Q, string](cols.ID.Expression),
		Name:        psql.Where[Q, string](cols.Name.Expression),
		Description: psql.WhereNull[Q, string](cols.Description.Expression),
		CreatedAt:   psql.Where[Q, time.Time](cols.CreatedAt.Expression),
		UpdatedAt:   psql.Where[Q, time.Time](cols.UpdatedAt.Expression),
		GroupInfo:   psql.WhereNull[Q, types.JSON[dto.GroupInfoBox]](cols.GroupInfo.Expression),
		R:           groupWhereR[Q]{cols: cols},
	}
}

// groupWhereR holds the relationship-based filters of
// groupWhere under the R namespace — mirroring the model's
// R struct — so they cannot collide with column-based filter fields.
type groupWhereR[Q psql.Filterable] struct {
	cols groupColumns
}

// HasUserGroups filters parents that have a matching UserGroups using a
// correlated EXISTS subquery (semi-join). Unlike an INNER JOIN it does not
// multiply parent rows, so no DISTINCT is needed. The optional filters are
// applied to the subquery (i.e. to UserGroups).
func (w groupWhereR[Q]) HasUserGroups(filters ...bob.Mod[*dialect.SelectQuery]) mods.Where[Q] {
	q := psql.Select(
		sm.Columns(psql.Raw("1")),
		sm.From(UserGroups.NameExpr()),
		sm.Where(UserGroups.Columns.GroupID.EQ(w.cols.ID)),
	)
	q.Apply(filters...)
	return mods.Where[Q]{E: psql.Exists(q)}
}

// NULL-tolerant scan buffer for groupScanMapperNullable:
// on a LEFT JOIN miss every column comes back NULL, so each field uses the
// nullable version of the column type even when the column itself is NOT NULL.
type groupPreloadBuf struct {
	ID          sql.Null[string]
	Name        sql.Null[string]
	Description sql.Null[string]
	CreatedAt   sql.Null[time.Time]
	UpdatedAt   sql.Null[time.Time]
	GroupInfo   sql.Null[types.JSON[dto.GroupInfoBox]]
}

// groupScanMapperNullable maps the preloaded group
// columns (prefixed with the runtime join alias) without reflection, while
// keeping the LEFT JOIN semantics of the reflection-based mapper: a row whose
// prefixed columns are all NULL yields nil (no child), and NULL values never
// error, they just leave the zero value in the field.
func groupScanMapperNullable(prefix string) scan.Mapper[*Group] {
	return func(ctx context.Context, cols []string) (scan.BeforeFunc, func(any) (*Group, error)) {
		// resolve the column names once per query, not per row
		type target struct {
			idx int
			dst func(b *groupPreloadBuf) any
		}
		targets := make([]target, 0, 6)
		for i, col := range cols {
			name, ok := strings.CutPrefix(col, prefix)
			if !ok {
				continue
			}
			switch name {
			case "id":
				targets = append(targets, target{i, func(b *groupPreloadBuf) any { return &b.ID }})
			case "name":
				targets = append(targets, target{i, func(b *groupPreloadBuf) any { return &b.Name }})
			case "description":
				targets = append(targets, target{i, func(b *groupPreloadBuf) any { return &b.Description }})
			case "created_at":
				targets = append(targets, target{i, func(b *groupPreloadBuf) any { return &b.CreatedAt }})
			case "updated_at":
				targets = append(targets, target{i, func(b *groupPreloadBuf) any { return &b.UpdatedAt }})
			case "group_info":
				targets = append(targets, target{i, func(b *groupPreloadBuf) any { return &b.GroupInfo }})
			}
		}

		// One scratch buffer reused for every row: before -> scan -> after runs
		// synchronously per row, the scheduled columns are fully overwritten each
		// row, and unselected columns stay zero, so a single buffer preserves the
		// per-row NULL semantics without allocating a buffer per parent row. The
		// returned child (o below) is always freshly allocated, so buf never
		// escapes past the after func.
		buf := new(groupPreloadBuf)
		return func(row *scan.Row) (any, error) {
				for _, t := range targets {
					row.ScheduleScanByIndex(t.idx, t.dst(buf))
				}
				return buf, nil
			}, func(link any) (*Group, error) {
				buf := link.(*groupPreloadBuf)

				// Same rule as the reflection mapper's row validator: the child
				// exists only if at least one of its columns is not NULL. Columns
				// not selected by the query are never scanned and stay invalid,
				// so this check also matches when only a subset is selected.
				if !(buf.ID.Valid) &&
					!(buf.Name.Valid) &&
					!(buf.Description.Valid) &&
					!(buf.CreatedAt.Valid) &&
					!(buf.UpdatedAt.Valid) &&
					!(buf.GroupInfo.Valid) {
					return nil, nil
				}

				o := new(Group)
				if buf.ID.Valid {
					o.ID = buf.ID.V
				}
				if buf.Name.Valid {
					o.Name = buf.Name.V
				}
				o.Description = buf.Description
				if buf.CreatedAt.Valid {
					o.CreatedAt = buf.CreatedAt.V
				}
				if buf.UpdatedAt.Valid {
					o.UpdatedAt = buf.UpdatedAt.V
				}
				o.GroupInfo = buf.GroupInfo
				return o, nil
			}
	}
}

func (o *Group) Preload(name string, retrieved any) error {
	if o == nil {
		return nil
	}

	switch name {
	case "UserGroups":
		rels, ok := retrieved.(UserGroupSlice)
		if !ok {
			return fmt.Errorf("group cannot load %T as %q", retrieved, name)
		}

		o.R.UserGroups = rels
		o.R.Loaded.UserGroups = true

		for _, rel := range rels {
			if rel != nil {
				rel.R.Group = o
				rel.R.Loaded.Group = true
			}
		}
		return nil
	default:
		return fmt.Errorf("group has no relationship %q", name)
	}
}

type groupPreloader struct{}

func buildGroupPreloader() groupPreloader {
	return groupPreloader{}
}

type groupThenLoader[Q orm.Loadable] struct {
	UserGroups func(...bob.Mod[*dialect.SelectQuery]) orm.Loader[Q]
}

func buildGroupThenLoader[Q orm.Loadable]() groupThenLoader[Q] {
	type UserGroupsLoadInterface interface {
		LoadUserGroups(context.Context, bob.Executor, ...bob.Mod[*dialect.SelectQuery]) error
	}

	return groupThenLoader[Q]{
		UserGroups: thenLoadBuilder[Q](
			"UserGroups",
			func(ctx context.Context, exec bob.Executor, retrieved UserGroupsLoadInterface, mods ...bob.Mod[*dialect.SelectQuery]) error {
				return retrieved.LoadUserGroups(ctx, exec, mods...)
			},
		),
	}
}

// LoadUserGroups loads the group's UserGroups into the .R struct
func (o *Group) LoadUserGroups(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if o == nil {
		return nil
	}

	// Reset the relationship
	o.R.UserGroups = nil
	o.R.Loaded.UserGroups = false

	related, err := o.UserGroups(mods...).All(ctx, exec)
	if err != nil {
		return err
	}

	for _, rel := range related {
		rel.R.Group = o
		rel.R.Loaded.Group = true
	}

	o.R.UserGroups = related
	o.R.Loaded.UserGroups = true
	return nil
}

// LoadUserGroups loads the group's UserGroups into the .R struct
func (os GroupSlice) LoadUserGroups(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if len(os) == 0 {
		return nil
	}

	userGroups, err := os.UserGroups(mods...).All(ctx, exec)
	if err != nil {
		return err
	}

	for _, o := range os {
		if o == nil {
			continue
		}

		o.R.UserGroups = nil
		o.R.Loaded.UserGroups = true
	}
	// O(N+M) stitch via a map keyed by the join column (key -> []parent; was O(N*M)).
	groupByKey := make(map[string][]*Group, len(os))
	for _, o := range os {
		if o == nil {
			continue
		}

		groupByKey[o.ID] = append(groupByKey[o.ID], o)
	}

	for _, rel := range userGroups {

		owners, ok := groupByKey[rel.GroupID]
		if !ok {
			continue
		}

		for _, o := range owners {

			rel.R.Group = o
			rel.R.Loaded.Group = true

			o.R.UserGroups = append(o.R.UserGroups, rel)

		}
	}

	return nil
}

// groupC is where relationship counts are stored.
type groupC struct {
	UserGroups *int64
}

// PreloadCount sets a count in the C struct by name
func (o *Group) PreloadCount(name string, count int64) error {
	if o == nil {
		return nil
	}

	switch name {
	case "UserGroups":
		o.C.UserGroups = &count
	}
	return nil
}

type groupCountPreloader struct {
	UserGroups func(...bob.Mod[*dialect.SelectQuery]) psql.Preloader
}

func buildGroupCountPreloader() groupCountPreloader {
	return groupCountPreloader{
		UserGroups: func(mods ...bob.Mod[*dialect.SelectQuery]) psql.Preloader {
			return countPreloader[*Group]("UserGroups", func(parent string) bob.Expression {
				// Build a correlated subquery: (SELECT COUNT(*) FROM related WHERE fk = parent.pk)
				if parent == "" {
					parent = Groups.Alias()
				}

				subqueryMods := []bob.Mod[*dialect.SelectQuery]{
					sm.Columns(psql.Raw("count(*)")),

					sm.From(UserGroups.NameAsExpr()),
					sm.Where(psql.Quote(UserGroups.Alias(), "group_id").EQ(psql.Quote(parent, "id"))),
				}
				subqueryMods = append(subqueryMods, mods...)
				return psql.Group(psql.Select(subqueryMods...).Expression)
			})
		},
	}
}

type groupCountThenLoader[Q orm.Loadable] struct {
	UserGroups func(...bob.Mod[*dialect.SelectQuery]) orm.Loader[Q]
}

func buildGroupCountThenLoader[Q orm.Loadable]() groupCountThenLoader[Q] {
	type UserGroupsCountInterface interface {
		LoadCountUserGroups(context.Context, bob.Executor, ...bob.Mod[*dialect.SelectQuery]) error
	}

	return groupCountThenLoader[Q]{
		UserGroups: countThenLoadBuilder[Q](
			"UserGroups",
			func(ctx context.Context, exec bob.Executor, retrieved UserGroupsCountInterface, mods ...bob.Mod[*dialect.SelectQuery]) error {
				return retrieved.LoadCountUserGroups(ctx, exec, mods...)
			},
		),
	}
}

// LoadCountUserGroups loads the count of UserGroups into the C struct
func (o *Group) LoadCountUserGroups(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if o == nil {
		return nil
	}

	count, err := o.UserGroups(mods...).Count(ctx, exec)
	if err != nil {
		return err
	}

	o.C.UserGroups = &count
	return nil
}

// LoadCountUserGroups loads the count of UserGroups for a slice in a single batch query
func (os GroupSlice) LoadCountUserGroups(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if len(os) == 0 {
		return nil
	}

	// Build the IN arg expression from parent PKs

	pkID := make(pgtypes.Array[string], 0, len(os))
	for _, o := range os {
		if o == nil {
			continue
		}
		pkID = append(pkID, o.ID)
	}
	PKArgExpr := psql.Any(psql.Cast(psql.Arg(pkID), "uuid[]"))

	// countResult holds one scanned row from the batch count query.
	// FK columns are aliased to the parent PK column names for direct map lookup.
	type countResult struct {
		ID    string
		Count int64
	}

	batchMods := []bob.Mod[*dialect.SelectQuery]{
		// SELECT fk AS parent_pk, count(*)
		sm.Columns(
			UserGroups.Columns.GroupID.As("id"),
			psql.Raw("count(*) as count"),
		),
		// Single-hop: FROM related table directly
		sm.From(UserGroups.NameAsExpr()),

		// WHERE fk IN (parent PKs) — psql single-column FK uses `= ANY(array)` (see PKArgExpr above)
		sm.Where(UserGroups.Columns.GroupID.EQ(PKArgExpr)),
		// GROUP BY fk columns
		sm.GroupBy(UserGroups.Columns.GroupID),
	}
	batchMods = append(batchMods, mods...)

	results, err := bob.All(ctx, exec,
		psql.Select(batchMods...),
		scan.StructMapper[countResult](),
	)
	if err != nil {
		return err
	}

	// Single-column FK: direct map lookup
	countMap := make(map[string]int64, len(results))
	for _, r := range results {
		countMap[r.ID] = r.Count
	}
	for _, o := range os {
		if o == nil {
			continue
		}
		count := countMap[o.ID]
		o.C.UserGroups = &count
	}

	return nil
}

type groupJoins[Q dialect.Joinable] struct {
	typ        string
	UserGroups modAs[Q, userGroupColumns]
}

func (j groupJoins[Q]) aliasedAs(alias string) groupJoins[Q] {
	return buildGroupJoins[Q](buildGroupColumns(alias), j.typ)
}

func buildGroupJoins[Q dialect.Joinable](cols groupColumns, typ string) groupJoins[Q] {
	return groupJoins[Q]{
		typ: typ,
		UserGroups: modAs[Q, userGroupColumns]{
			c: UserGroups.Columns,
			f: func(to userGroupColumns) bob.Mod[Q] {
				mods := make(mods.QueryMods[Q], 0, 1)

				{
					mods = append(mods, dialect.Join[Q](typ, UserGroups.NameExpr().As(to.Alias())).On(
						to.GroupID.EQ(cols.ID),
					))
				}

				return mods
			},
		},
	}
}
