// Code generated by BobGen sql v0.49.0. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package model

import (
	"context"
	"fmt"
	"io"
	"time"

	"github.com/stephenafamo/bob"
	"github.com/stephenafamo/bob/dialect/psql"
	"github.com/stephenafamo/bob/dialect/psql/dialect"
	"github.com/stephenafamo/bob/dialect/psql/dm"
	"github.com/stephenafamo/bob/dialect/psql/sm"
	"github.com/stephenafamo/bob/dialect/psql/um"
	"github.com/stephenafamo/bob/expr"
	"github.com/stephenafamo/bob/mods"
	"github.com/stephenafamo/bob/orm"
	"github.com/stephenafamo/bob/types/pgtypes"
	"github.com/stephenafamo/scan"
)

// UserGroup is an object representing the database table.
type UserGroup struct {
	UserID   string    `db:"user_id,pk" `
	GroupID  string    `db:"group_id,pk" `
	JoinedAt time.Time `db:"joined_at" `

	R userGroupR `db:"-" `
}

// UserGroupSlice is an alias for a slice of pointers to UserGroup.
// This should almost always be used instead of []*UserGroup.
type UserGroupSlice []*UserGroup

// UserGroups contains methods to work with the user_groups table
var UserGroups = psql.NewTablex[*UserGroup, UserGroupSlice, *UserGroupSetter]("", "user_groups", buildUserGroupColumns("user_groups"), userGroupScanMapper)

// UserGroupsQuery is a query on the user_groups table
type UserGroupsQuery = *psql.ViewQuery[*UserGroup, UserGroupSlice]

// userGroupR is where relationships are stored.
type userGroupR struct {
	Group *Group // user_groups.user_groups_group_id_fkey
	User  *User  // user_groups.user_groups_user_id_fkey
	// Loaded reports whether each relationship has been loaded.
	// A relationship's bool is set by Load*, Preload, ThenLoad, factory builds,
	// and to-one Attach/Insert operations. To-many Attach/Insert operations leave it unchanged.
	Loaded userGroupRLoaded `db:"-" `
}

// userGroupRLoaded tracks which relationships on UserGroup have been loaded.
type userGroupRLoaded struct {
	Group bool // user_groups.user_groups_group_id_fkey
	User  bool // user_groups.user_groups_user_id_fkey
}

func buildUserGroupColumns(tableName string) userGroupColumns {
	columnsExpr := expr.NewColumnsExpr(
		"user_id", "group_id", "joined_at",
	)

	if tableName != "" {
		columnsExpr = columnsExpr.WithParent(tableName)
	}

	return userGroupColumns{
		ColumnsExpr: columnsExpr,
		tableAlias:  tableName,
		UserID:      buildUserGroupColumn(tableName, "user_id"),
		GroupID:     buildUserGroupColumn(tableName, "group_id"),
		JoinedAt:    buildUserGroupColumn(tableName, "joined_at"),
	}
}

type userGroupColumns struct {
	expr.ColumnsExpr
	tableAlias string
	UserID     userGroupColumn
	GroupID    userGroupColumn
	JoinedAt   userGroupColumn
}

// Alias returns the current table alias for the columns set.
func (c userGroupColumns) Alias() string {
	return c.tableAlias
}

// AliasedAs returns a copy of the columns set qualified by tableName.
func (userGroupColumns) AliasedAs(tableName string) userGroupColumns {
	return buildUserGroupColumns(tableName)
}

// Unqualified returns a copy of the columns set without table qualification.
func (c userGroupColumns) Unqualified() userGroupColumns {
	return buildUserGroupColumns("")
}

func buildUserGroupColumn(alias, name string) userGroupColumn {
	return userGroupColumn{
		Expression: psql.Quote(alias, name),
		alias:      alias,
		name:       name,
	}
}

type userGroupColumn struct {
	psql.Expression
	alias string
	name  string
}

// Name returns the unqualified column name.
func (c userGroupColumn) Name() string {
	return c.name
}

// ShouldOmitParens prevents automatic parenthesis wrapping in expression builders.
func (c userGroupColumn) ShouldOmitParens() bool {
	return true
}

// UserGroupSetter is used for insert/upsert/update operations
// All values are optional, and do not have to be set
// Generated columns are not included
type UserGroupSetter struct {
	UserID   *string    `db:"user_id,pk" `
	GroupID  *string    `db:"group_id,pk" `
	JoinedAt *time.Time `db:"joined_at" `
}

func (s UserGroupSetter) SetColumns() []string {
	vals := make([]string, 0, 3)
	if s.UserID != nil {
		vals = append(vals, "user_id")
	}
	if s.GroupID != nil {
		vals = append(vals, "group_id")
	}
	if s.JoinedAt != nil {
		vals = append(vals, "joined_at")
	}
	return vals
}

func (s UserGroupSetter) Overwrite(t *UserGroup) {
	if s.UserID != nil {
		t.UserID = func() string {
			if s.UserID == nil {
				return *new(string)
			}
			return *s.UserID
		}()
	}
	if s.GroupID != nil {
		t.GroupID = func() string {
			if s.GroupID == nil {
				return *new(string)
			}
			return *s.GroupID
		}()
	}
	if s.JoinedAt != nil {
		t.JoinedAt = func() time.Time {
			if s.JoinedAt == nil {
				return *new(time.Time)
			}
			return *s.JoinedAt
		}()
	}
}

func (s *UserGroupSetter) Apply(q *dialect.InsertQuery) {
	q.AppendHooks(func(ctx context.Context, exec bob.Executor) (context.Context, error) {
		return UserGroups.BeforeInsertHooks.RunHooks(ctx, exec, s)
	})

	q.AppendValues(
		bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
			if s.UserID == nil {
				return psql.Raw("DEFAULT").WriteSQL(ctx, w, d, start)
			}
			return psql.Arg(func() string {
				if s.UserID == nil {
					return *new(string)
				}
				return *s.UserID
			}()).WriteSQL(ctx, w, d, start)
		}), bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
			if s.GroupID == nil {
				return psql.Raw("DEFAULT").WriteSQL(ctx, w, d, start)
			}
			return psql.Arg(func() string {
				if s.GroupID == nil {
					return *new(string)
				}
				return *s.GroupID
			}()).WriteSQL(ctx, w, d, start)
		}), bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
			if s.JoinedAt == nil {
				return psql.Raw("DEFAULT").WriteSQL(ctx, w, d, start)
			}
			return psql.Arg(func() time.Time {
				if s.JoinedAt == nil {
					return *new(time.Time)
				}
				return *s.JoinedAt
			}()).WriteSQL(ctx, w, d, start)
		}))
}

func (s UserGroupSetter) UpdateMod() bob.Mod[*dialect.UpdateQuery] {
	return um.Set(s.Expressions()...)
}

func (s UserGroupSetter) Expressions(prefix ...string) []bob.Expression {
	exprs := make([]bob.Expression, 0, 3)

	if s.UserID != nil {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "user_id")...),
			psql.Arg(s.UserID),
		}})
	}

	if s.GroupID != nil {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "group_id")...),
			psql.Arg(s.GroupID),
		}})
	}

	if s.JoinedAt != nil {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "joined_at")...),
			psql.Arg(s.JoinedAt),
		}})
	}

	return exprs
}

// scan.Mapper[*T] without reflection: maps columns to fields by index.
func userGroupScanMapper(ctx context.Context, cols []string) (scan.BeforeFunc, func(any) (*UserGroup, error)) {
	// resolve the column positions once per query, not per row
	type target struct {
		idx int
		dst func(o *UserGroup) any
	}
	targets := make([]target, 0, 3)
	for i, col := range cols {
		switch col {
		case "user_id":
			targets = append(targets, target{i, func(o *UserGroup) any { return &o.UserID }})
		case "group_id":
			targets = append(targets, target{i, func(o *UserGroup) any { return &o.GroupID }})
		case "joined_at":
			targets = append(targets, target{i, func(o *UserGroup) any { return &o.JoinedAt }})
		}
	}

	return func(row *scan.Row) (any, error) {
			o := new(UserGroup)
			for _, t := range targets {
				row.ScheduleScanByIndex(t.idx, t.dst(o))
			}
			return o, nil
		}, func(v any) (*UserGroup, error) {
			return v.(*UserGroup), nil
		}
}

// FindUserGroup retrieves a single record by primary key
// If cols is empty Find will return all columns.
func FindUserGroup(ctx context.Context, exec bob.Executor, UserIDPK string, GroupIDPK string, cols ...string) (*UserGroup, error) {
	if len(cols) == 0 {
		return UserGroups.Query(
			sm.Where(UserGroups.Columns.UserID.EQ(psql.Arg(UserIDPK))),
			sm.Where(UserGroups.Columns.GroupID.EQ(psql.Arg(GroupIDPK))),
		).One(ctx, exec)
	}

	return UserGroups.Query(
		sm.Where(UserGroups.Columns.UserID.EQ(psql.Arg(UserIDPK))),
		sm.Where(UserGroups.Columns.GroupID.EQ(psql.Arg(GroupIDPK))),
		sm.Columns(UserGroups.Columns.Only(cols...)),
	).One(ctx, exec)
}

// UserGroupExists checks the presence of a single record by primary key
func UserGroupExists(ctx context.Context, exec bob.Executor, UserIDPK string, GroupIDPK string) (bool, error) {
	return UserGroups.Query(
		sm.Where(UserGroups.Columns.UserID.EQ(psql.Arg(UserIDPK))),
		sm.Where(UserGroups.Columns.GroupID.EQ(psql.Arg(GroupIDPK))),
	).Exists(ctx, exec)
}

// AfterQueryHook is called after UserGroup is retrieved from the database
func (o *UserGroup) AfterQueryHook(ctx context.Context, exec bob.Executor, queryType bob.QueryType) error {
	var err error

	switch queryType {
	case bob.QueryTypeSelect:
		ctx, err = UserGroups.AfterSelectHooks.RunHooks(ctx, exec, UserGroupSlice{o})
	case bob.QueryTypeInsert:
		ctx, err = UserGroups.AfterInsertHooks.RunHooks(ctx, exec, UserGroupSlice{o})
	case bob.QueryTypeUpdate:
		ctx, err = UserGroups.AfterUpdateHooks.RunHooks(ctx, exec, UserGroupSlice{o})
	case bob.QueryTypeDelete:
		ctx, err = UserGroups.AfterDeleteHooks.RunHooks(ctx, exec, UserGroupSlice{o})
	case bob.QueryTypeMerge:
		ctx, err = UserGroups.AfterMergeHooks.RunHooks(ctx, exec, UserGroupSlice{o})
	}

	return err
}

// primaryKeyVals returns the primary key values of the UserGroup
func (o *UserGroup) primaryKeyVals() bob.Expression {
	return psql.ArgGroup(
		o.UserID,
		o.GroupID,
	)
}

func (o *UserGroup) pkEQ() dialect.Expression {
	return psql.Group(psql.Quote("user_groups", "user_id"), psql.Quote("user_groups", "group_id")).EQ(bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
		return o.primaryKeyVals().WriteSQL(ctx, w, d, start)
	}))
}

// Update uses an executor to update the UserGroup
func (o *UserGroup) Update(ctx context.Context, exec bob.Executor, s *UserGroupSetter) error {
	v, err := UserGroups.Update(s.UpdateMod(), um.Where(o.pkEQ())).One(ctx, exec)
	if err != nil {
		return err
	}

	o.R = v.R
	*o = *v

	return nil
}

// Delete deletes a single UserGroup record with an executor
func (o *UserGroup) Delete(ctx context.Context, exec bob.Executor) error {
	_, err := UserGroups.Delete(dm.Where(o.pkEQ())).Exec(ctx, exec)
	return err
}

// Reload refreshes the UserGroup using the executor
func (o *UserGroup) Reload(ctx context.Context, exec bob.Executor) error {
	o2, err := UserGroups.Query(
		sm.Where(UserGroups.Columns.UserID.EQ(psql.Arg(o.UserID))),
		sm.Where(UserGroups.Columns.GroupID.EQ(psql.Arg(o.GroupID))),
	).One(ctx, exec)
	if err != nil {
		return err
	}
	o2.R = o.R
	*o = *o2

	return nil
}

// AfterQueryHook is called after UserGroupSlice is retrieved from the database
func (o UserGroupSlice) AfterQueryHook(ctx context.Context, exec bob.Executor, queryType bob.QueryType) error {
	var err error

	switch queryType {
	case bob.QueryTypeSelect:
		ctx, err = UserGroups.AfterSelectHooks.RunHooks(ctx, exec, o)
	case bob.QueryTypeInsert:
		ctx, err = UserGroups.AfterInsertHooks.RunHooks(ctx, exec, o)
	case bob.QueryTypeUpdate:
		ctx, err = UserGroups.AfterUpdateHooks.RunHooks(ctx, exec, o)
	case bob.QueryTypeDelete:
		ctx, err = UserGroups.AfterDeleteHooks.RunHooks(ctx, exec, o)
	case bob.QueryTypeMerge:
		ctx, err = UserGroups.AfterMergeHooks.RunHooks(ctx, exec, o)
	}

	return err
}

func (o UserGroupSlice) pkIN() dialect.Expression {
	if len(o) == 0 {
		return psql.Raw("NULL")
	}

	return psql.Group(psql.Quote("user_groups", "user_id"), psql.Quote("user_groups", "group_id")).In(bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
		pkPairs := make([]bob.Expression, len(o))
		for i, row := range o {
			pkPairs[i] = row.primaryKeyVals()
		}
		return bob.ExpressSlice(ctx, w, d, start, pkPairs, "", ", ", "")
	}))
}

// copyMatchingRows finds models in the given slice that have the same primary key
// then it first copies the existing relationships from the old model to the new model
// and then replaces the old model in the slice with the new model
func (o UserGroupSlice) copyMatchingRows(from ...*UserGroup) {
	for i, old := range o {
		for _, new := range from {
			if new.UserID != old.UserID {
				continue
			}
			if new.GroupID != old.GroupID {
				continue
			}
			new.R = old.R
			o[i] = new
			break
		}
	}
}

// UpdateMod modifies an update query with "WHERE primary_key IN (o...)"
func (o UserGroupSlice) UpdateMod() bob.Mod[*dialect.UpdateQuery] {
	return bob.ModFunc[*dialect.UpdateQuery](func(q *dialect.UpdateQuery) {
		q.AppendHooks(func(ctx context.Context, exec bob.Executor) (context.Context, error) {
			return UserGroups.BeforeUpdateHooks.RunHooks(ctx, exec, o)
		})

		q.AppendLoader(bob.LoaderFunc(func(ctx context.Context, exec bob.Executor, retrieved any) error {
			var err error
			switch retrieved := retrieved.(type) {
			case *UserGroup:
				o.copyMatchingRows(retrieved)
			case []*UserGroup:
				o.copyMatchingRows(retrieved...)
			case UserGroupSlice:
				o.copyMatchingRows(retrieved...)
			default:
				// If the retrieved value is not a UserGroup or a slice of UserGroup
				// then run the AfterUpdateHooks on the slice
				_, err = UserGroups.AfterUpdateHooks.RunHooks(ctx, exec, o)
			}

			return err
		}))

		q.AppendWhere(o.pkIN())
	})
}

// DeleteMod modifies an delete query with "WHERE primary_key IN (o...)"
func (o UserGroupSlice) DeleteMod() bob.Mod[*dialect.DeleteQuery] {
	return bob.ModFunc[*dialect.DeleteQuery](func(q *dialect.DeleteQuery) {
		q.AppendHooks(func(ctx context.Context, exec bob.Executor) (context.Context, error) {
			return UserGroups.BeforeDeleteHooks.RunHooks(ctx, exec, o)
		})

		q.AppendLoader(bob.LoaderFunc(func(ctx context.Context, exec bob.Executor, retrieved any) error {
			var err error
			switch retrieved := retrieved.(type) {
			case *UserGroup:
				o.copyMatchingRows(retrieved)
			case []*UserGroup:
				o.copyMatchingRows(retrieved...)
			case UserGroupSlice:
				o.copyMatchingRows(retrieved...)
			default:
				// If the retrieved value is not a UserGroup or a slice of UserGroup
				// then run the AfterDeleteHooks on the slice
				_, err = UserGroups.AfterDeleteHooks.RunHooks(ctx, exec, o)
			}

			return err
		}))

		q.AppendWhere(o.pkIN())
	})
}

// MergeMod modifies a merge query to run BeforeMergeHooks and AfterMergeHooks
// and updates the slice with the returned rows.
func (o UserGroupSlice) MergeMod() bob.Mod[*dialect.MergeQuery] {
	return bob.ModFunc[*dialect.MergeQuery](func(q *dialect.MergeQuery) {
		q.AppendHooks(func(ctx context.Context, exec bob.Executor) (context.Context, error) {
			return UserGroups.BeforeMergeHooks.RunHooks(ctx, exec, o)
		})

		q.AppendLoader(bob.LoaderFunc(func(ctx context.Context, exec bob.Executor, retrieved any) error {
			var err error
			switch retrieved := retrieved.(type) {
			case *UserGroup:
				o.copyMatchingRows(retrieved)
			case []*UserGroup:
				o.copyMatchingRows(retrieved...)
			case UserGroupSlice:
				o.copyMatchingRows(retrieved...)
			default:
				// If the retrieved value is not a UserGroup or a slice of UserGroup
				// then run the AfterMergeHooks on the slice
				_, err = UserGroups.AfterMergeHooks.RunHooks(ctx, exec, o)
			}

			return err
		}))
	})
}

func (o UserGroupSlice) UpdateAll(ctx context.Context, exec bob.Executor, vals UserGroupSetter) error {
	if len(o) == 0 {
		return nil
	}

	_, err := UserGroups.Update(vals.UpdateMod(), o.UpdateMod()).All(ctx, exec)
	return err
}

func (o UserGroupSlice) DeleteAll(ctx context.Context, exec bob.Executor) error {
	if len(o) == 0 {
		return nil
	}

	_, err := UserGroups.Delete(o.DeleteMod()).Exec(ctx, exec)
	return err
}

func (o UserGroupSlice) ReloadAll(ctx context.Context, exec bob.Executor) error {
	if len(o) == 0 {
		return nil
	}

	o2, err := UserGroups.Query(sm.Where(o.pkIN())).All(ctx, exec)
	if err != nil {
		return err
	}

	o.copyMatchingRows(o2...)

	return nil
}

// Group starts a query for related objects on groups
func (o *UserGroup) Group(mods ...bob.Mod[*dialect.SelectQuery]) GroupsQuery {
	return Groups.Query(append(mods,
		sm.Where(Groups.Columns.ID.EQ(psql.Arg(o.GroupID))),
	)...)
}

func (os UserGroupSlice) Group(mods ...bob.Mod[*dialect.SelectQuery]) GroupsQuery {
	pkGroupID := make(pgtypes.Array[string], 0, len(os))
	for _, o := range os {
		if o == nil {
			continue
		}
		pkGroupID = append(pkGroupID, o.GroupID)
	}

	PKArgExpr := psql.Any(psql.Cast(psql.Arg(pkGroupID), "uuid[]"))

	return Groups.Query(append(mods,
		sm.Where(Groups.Columns.ID.EQ(PKArgExpr)),
	)...)
}

// User starts a query for related objects on users
func (o *UserGroup) User(mods ...bob.Mod[*dialect.SelectQuery]) UsersQuery {
	return Users.Query(append(mods,
		sm.Where(Users.Columns.ID.EQ(psql.Arg(o.UserID))),
	)...)
}

func (os UserGroupSlice) User(mods ...bob.Mod[*dialect.SelectQuery]) UsersQuery {
	pkUserID := make(pgtypes.Array[string], 0, len(os))
	for _, o := range os {
		if o == nil {
			continue
		}
		pkUserID = append(pkUserID, o.UserID)
	}

	PKArgExpr := psql.Any(psql.Cast(psql.Arg(pkUserID), "uuid[]"))

	return Users.Query(append(mods,
		sm.Where(Users.Columns.ID.EQ(PKArgExpr)),
	)...)
}

func attachUserGroupGroup0(ctx context.Context, exec bob.Executor, count int, userGroup0 *UserGroup, group1 *Group) (*UserGroup, error) {
	setter := &UserGroupSetter{
		GroupID: func() *string { return &group1.ID }(),
	}

	err := userGroup0.Update(ctx, exec, setter)
	if err != nil {
		return nil, fmt.Errorf("attachUserGroupGroup0: %w", err)
	}

	return userGroup0, nil
}

func (userGroup0 *UserGroup) InsertGroup(ctx context.Context, exec bob.Executor, related *GroupSetter) error {
	var err error

	group1, err := Groups.Insert(related).One(ctx, exec)
	if err != nil {
		return fmt.Errorf("inserting related objects: %w", err)
	}

	_, err = attachUserGroupGroup0(ctx, exec, 1, userGroup0, group1)
	if err != nil {
		return err
	}

	userGroup0.R.Group = group1
	userGroup0.R.Loaded.Group = true

	group1.R.UserGroups = append(group1.R.UserGroups, userGroup0)

	return nil
}

func (userGroup0 *UserGroup) AttachGroup(ctx context.Context, exec bob.Executor, group1 *Group) error {
	var err error

	_, err = attachUserGroupGroup0(ctx, exec, 1, userGroup0, group1)
	if err != nil {
		return err
	}

	userGroup0.R.Group = group1
	userGroup0.R.Loaded.Group = true

	group1.R.UserGroups = append(group1.R.UserGroups, userGroup0)

	return nil
}

func attachUserGroupUser0(ctx context.Context, exec bob.Executor, count int, userGroup0 *UserGroup, user1 *User) (*UserGroup, error) {
	setter := &UserGroupSetter{
		UserID: func() *string { return &user1.ID }(),
	}

	err := userGroup0.Update(ctx, exec, setter)
	if err != nil {
		return nil, fmt.Errorf("attachUserGroupUser0: %w", err)
	}

	return userGroup0, nil
}

func (userGroup0 *UserGroup) InsertUser(ctx context.Context, exec bob.Executor, related *UserSetter) error {
	var err error

	user1, err := Users.Insert(related).One(ctx, exec)
	if err != nil {
		return fmt.Errorf("inserting related objects: %w", err)
	}

	_, err = attachUserGroupUser0(ctx, exec, 1, userGroup0, user1)
	if err != nil {
		return err
	}

	userGroup0.R.User = user1
	userGroup0.R.Loaded.User = true

	user1.R.UserGroups = append(user1.R.UserGroups, userGroup0)

	return nil
}

func (userGroup0 *UserGroup) AttachUser(ctx context.Context, exec bob.Executor, user1 *User) error {
	var err error

	_, err = attachUserGroupUser0(ctx, exec, 1, userGroup0, user1)
	if err != nil {
		return err
	}

	userGroup0.R.User = user1
	userGroup0.R.Loaded.User = true

	user1.R.UserGroups = append(user1.R.UserGroups, userGroup0)

	return nil
}

type userGroupWhere[Q psql.Filterable] struct {
	cols     userGroupColumns
	UserID   psql.WhereMod[Q, string]
	GroupID  psql.WhereMod[Q, string]
	JoinedAt psql.WhereMod[Q, time.Time]
	R        userGroupWhereR[Q]
}

func (userGroupWhere[Q]) AliasedAs(alias string) userGroupWhere[Q] {
	return buildUserGroupWhere[Q](buildUserGroupColumns(alias))
}

func buildUserGroupWhere[Q psql.Filterable](cols userGroupColumns) userGroupWhere[Q] {
	return userGroupWhere[Q]{
		cols:     cols,
		UserID:   psql.Where[Q, string](cols.UserID.Expression),
		GroupID:  psql.Where[Q, string](cols.GroupID.Expression),
		JoinedAt: psql.Where[Q, time.Time](cols.JoinedAt.Expression),
		R:        userGroupWhereR[Q]{cols: cols},
	}
}

// userGroupWhereR holds the relationship-based filters of
// userGroupWhere under the R namespace — mirroring the model's
// R struct — so they cannot collide with column-based filter fields.
type userGroupWhereR[Q psql.Filterable] struct {
	cols userGroupColumns
}

// HasGroup filters parents that have a matching Group using a
// correlated EXISTS subquery (semi-join). Unlike an INNER JOIN it does not
// multiply parent rows, so no DISTINCT is needed. The optional filters are
// applied to the subquery (i.e. to Groups).
func (w userGroupWhereR[Q]) HasGroup(filters ...bob.Mod[*dialect.SelectQuery]) mods.Where[Q] {
	q := psql.Select(
		sm.Columns(psql.Raw("1")),
		sm.From(Groups.NameExpr()),
		sm.Where(Groups.Columns.ID.EQ(w.cols.GroupID)),
	)
	q.Apply(filters...)
	return mods.Where[Q]{E: psql.Exists(q)}
}

// HasUser filters parents that have a matching User using a
// correlated EXISTS subquery (semi-join). Unlike an INNER JOIN it does not
// multiply parent rows, so no DISTINCT is needed. The optional filters are
// applied to the subquery (i.e. to Users).
func (w userGroupWhereR[Q]) HasUser(filters ...bob.Mod[*dialect.SelectQuery]) mods.Where[Q] {
	q := psql.Select(
		sm.Columns(psql.Raw("1")),
		sm.From(Users.NameExpr()),
		sm.Where(Users.Columns.ID.EQ(w.cols.UserID)),
	)
	q.Apply(filters...)
	return mods.Where[Q]{E: psql.Exists(q)}
}

func (o *UserGroup) Preload(name string, retrieved any) error {
	if o == nil {
		return nil
	}

	switch name {
	case "Group":
		rel, ok := retrieved.(*Group)
		if !ok {
			return fmt.Errorf("userGroup cannot load %T as %q", retrieved, name)
		}

		o.R.Group = rel
		o.R.Loaded.Group = true

		if rel != nil {
			rel.R.UserGroups = UserGroupSlice{o}
		}
		return nil
	case "User":
		rel, ok := retrieved.(*User)
		if !ok {
			return fmt.Errorf("userGroup cannot load %T as %q", retrieved, name)
		}

		o.R.User = rel
		o.R.Loaded.User = true

		if rel != nil {
			rel.R.UserGroups = UserGroupSlice{o}
		}
		return nil
	default:
		return fmt.Errorf("userGroup has no relationship %q", name)
	}
}

type userGroupPreloader struct {
	Group func(...psql.PreloadOption) psql.Preloader
	User  func(...psql.PreloadOption) psql.Preloader
}

func buildUserGroupPreloader() userGroupPreloader {
	return userGroupPreloader{
		Group: func(opts ...psql.PreloadOption) psql.Preloader {
			return psql.Preload[*Group, GroupSlice](psql.PreloadRel{
				Name: "Group",
				Sides: []psql.PreloadSide{
					{
						From:        UserGroups,
						To:          Groups,
						FromColumns: []string{"group_id"},
						ToColumns:   []string{"id"},
					},
				},
			}, Groups.Columns.Names(), groupScanMapperNullable, opts...)
		},
		User: func(opts ...psql.PreloadOption) psql.Preloader {
			return psql.Preload[*User, UserSlice](psql.PreloadRel{
				Name: "User",
				Sides: []psql.PreloadSide{
					{
						From:        UserGroups,
						To:          Users,
						FromColumns: []string{"user_id"},
						ToColumns:   []string{"id"},
					},
				},
			}, Users.Columns.Names(), userScanMapperNullable, opts...)
		},
	}
}

type userGroupThenLoader[Q orm.Loadable] struct {
	Group func(...bob.Mod[*dialect.SelectQuery]) orm.Loader[Q]
	User  func(...bob.Mod[*dialect.SelectQuery]) orm.Loader[Q]
}

func buildUserGroupThenLoader[Q orm.Loadable]() userGroupThenLoader[Q] {
	type GroupLoadInterface interface {
		LoadGroup(context.Context, bob.Executor, ...bob.Mod[*dialect.SelectQuery]) error
	}
	type UserLoadInterface interface {
		LoadUser(context.Context, bob.Executor, ...bob.Mod[*dialect.SelectQuery]) error
	}

	return userGroupThenLoader[Q]{
		Group: thenLoadBuilder[Q](
			"Group",
			func(ctx context.Context, exec bob.Executor, retrieved GroupLoadInterface, mods ...bob.Mod[*dialect.SelectQuery]) error {
				return retrieved.LoadGroup(ctx, exec, mods...)
			},
		),
		User: thenLoadBuilder[Q](
			"User",
			func(ctx context.Context, exec bob.Executor, retrieved UserLoadInterface, mods ...bob.Mod[*dialect.SelectQuery]) error {
				return retrieved.LoadUser(ctx, exec, mods...)
			},
		),
	}
}

// LoadGroup loads the userGroup's Group into the .R struct
func (o *UserGroup) LoadGroup(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if o == nil {
		return nil
	}

	// Reset the relationship
	o.R.Group = nil
	o.R.Loaded.Group = false

	related, err := o.Group(mods...).One(ctx, exec)
	if err != nil {
		return err
	}

	related.R.UserGroups = UserGroupSlice{o}

	o.R.Group = related
	o.R.Loaded.Group = true
	return nil
}

// LoadGroup loads the userGroup's Group into the .R struct
func (os UserGroupSlice) LoadGroup(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if len(os) == 0 {
		return nil
	}

	groups, err := os.Group(mods...).All(ctx, exec)
	if err != nil {
		return err
	}

	for _, o := range os {
		if o == nil {
			continue
		}

		o.R.Group = nil
		o.R.Loaded.Group = true
	}
	// O(N+M) stitch via a map keyed by the join column (key -> []parent; was O(N*M)).
	userGroupByKey := make(map[string][]*UserGroup, len(os))
	for _, o := range os {
		if o == nil {
			continue
		}

		userGroupByKey[o.GroupID] = append(userGroupByKey[o.GroupID], o)
	}

	for _, rel := range groups {

		owners, ok := userGroupByKey[rel.ID]
		if !ok {
			continue
		}

		for _, o := range owners {

			// to-one: keep only the first matching child (matches the previous break)
			if o.R.Group != nil {
				continue
			}

			rel.R.UserGroups = append(rel.R.UserGroups, o)

			o.R.Group = rel

		}
	}

	return nil
}

// LoadUser loads the userGroup's User into the .R struct
func (o *UserGroup) LoadUser(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if o == nil {
		return nil
	}

	// Reset the relationship
	o.R.User = nil
	o.R.Loaded.User = false

	related, err := o.User(mods...).One(ctx, exec)
	if err != nil {
		return err
	}

	related.R.UserGroups = UserGroupSlice{o}

	o.R.User = related
	o.R.Loaded.User = true
	return nil
}

// LoadUser loads the userGroup's User into the .R struct
func (os UserGroupSlice) LoadUser(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if len(os) == 0 {
		return nil
	}

	users, err := os.User(mods...).All(ctx, exec)
	if err != nil {
		return err
	}

	for _, o := range os {
		if o == nil {
			continue
		}

		o.R.User = nil
		o.R.Loaded.User = true
	}
	// O(N+M) stitch via a map keyed by the join column (key -> []parent; was O(N*M)).
	userGroupByKey := make(map[string][]*UserGroup, len(os))
	for _, o := range os {
		if o == nil {
			continue
		}

		userGroupByKey[o.UserID] = append(userGroupByKey[o.UserID], o)
	}

	for _, rel := range users {

		owners, ok := userGroupByKey[rel.ID]
		if !ok {
			continue
		}

		for _, o := range owners {

			// to-one: keep only the first matching child (matches the previous break)
			if o.R.User != nil {
				continue
			}

			rel.R.UserGroups = append(rel.R.UserGroups, o)

			o.R.User = rel

		}
	}

	return nil
}

type userGroupJoins[Q dialect.Joinable] struct {
	typ   string
	Group modAs[Q, groupColumns]
	User  modAs[Q, userColumns]
}

func (j userGroupJoins[Q]) aliasedAs(alias string) userGroupJoins[Q] {
	return buildUserGroupJoins[Q](buildUserGroupColumns(alias), j.typ)
}

func buildUserGroupJoins[Q dialect.Joinable](cols userGroupColumns, typ string) userGroupJoins[Q] {
	return userGroupJoins[Q]{
		typ: typ,
		Group: modAs[Q, groupColumns]{
			c: Groups.Columns,
			f: func(to groupColumns) bob.Mod[Q] {
				mods := make(mods.QueryMods[Q], 0, 1)

				{
					mods = append(mods, dialect.Join[Q](typ, Groups.NameExpr().As(to.Alias())).On(
						to.ID.EQ(cols.GroupID),
					))
				}

				return mods
			},
		},
		User: modAs[Q, userColumns]{
			c: Users.Columns,
			f: func(to userColumns) bob.Mod[Q] {
				mods := make(mods.QueryMods[Q], 0, 1)

				{
					mods = append(mods, dialect.Join[Q](typ, Users.NameExpr().As(to.Alias())).On(
						to.ID.EQ(cols.UserID),
					))
				}

				return mods
			},
		},
	}
}
