// Code generated by BobGen sql v0.49.0. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package model

import (
	"context"
	"database/sql"
	"fmt"
	"io"
	"strings"
	"time"

	"github.com/manhrev/gorest/internal/dto"
	"github.com/stephenafamo/bob"
	"github.com/stephenafamo/bob/dialect/psql"
	"github.com/stephenafamo/bob/dialect/psql/dialect"
	"github.com/stephenafamo/bob/dialect/psql/dm"
	"github.com/stephenafamo/bob/dialect/psql/sm"
	"github.com/stephenafamo/bob/dialect/psql/um"
	"github.com/stephenafamo/bob/expr"
	"github.com/stephenafamo/bob/mods"
	"github.com/stephenafamo/bob/orm"
	"github.com/stephenafamo/bob/types"
	"github.com/stephenafamo/bob/types/pgtypes"
	"github.com/stephenafamo/scan"
)

// User is an object representing the database table.
type User struct {
	ID        string                                `db:"id,pk" `
	Username  string                                `db:"username" `
	Email     string                                `db:"email" `
	FirstName string                                `db:"first_name" `
	LastName  string                                `db:"last_name" `
	CreatedAt time.Time                             `db:"created_at" `
	UpdatedAt time.Time                             `db:"updated_at" `
	Meta      sql.Null[types.JSON[dto.UserMetaBox]] `db:"meta" `

	R userR `db:"-" `

	C userC `db:"-" `
}

// UserSlice is an alias for a slice of pointers to User.
// This should almost always be used instead of []*User.
type UserSlice []*User

// Users contains methods to work with the users table
var Users = psql.NewTablex[*User, UserSlice, *UserSetter]("", "users", buildUserColumns("users"), userScanMapper)

// UsersQuery is a query on the users table
type UsersQuery = *psql.ViewQuery[*User, UserSlice]

// userR is where relationships are stored.
type userR struct {
	UserGroups UserGroupSlice // user_groups.user_groups_user_id_fkey
	// Loaded reports whether each relationship has been loaded.
	// A relationship's bool is set by Load*, Preload, ThenLoad, factory builds,
	// and to-one Attach/Insert operations. To-many Attach/Insert operations leave it unchanged.
	Loaded userRLoaded `db:"-" `
}

// userRLoaded tracks which relationships on User have been loaded.
type userRLoaded struct {
	UserGroups bool // user_groups.user_groups_user_id_fkey
}

func buildUserColumns(tableName string) userColumns {
	columnsExpr := expr.NewColumnsExpr(
		"id", "username", "email", "first_name", "last_name", "created_at", "updated_at", "meta",
	)

	if tableName != "" {
		columnsExpr = columnsExpr.WithParent(tableName)
	}

	return userColumns{
		ColumnsExpr: columnsExpr,
		tableAlias:  tableName,
		ID:          buildUserColumn(tableName, "id"),
		Username:    buildUserColumn(tableName, "username"),
		Email:       buildUserColumn(tableName, "email"),
		FirstName:   buildUserColumn(tableName, "first_name"),
		LastName:    buildUserColumn(tableName, "last_name"),
		CreatedAt:   buildUserColumn(tableName, "created_at"),
		UpdatedAt:   buildUserColumn(tableName, "updated_at"),
		Meta:        buildUserColumn(tableName, "meta"),
	}
}

type userColumns struct {
	expr.ColumnsExpr
	tableAlias string
	ID         userColumn
	Username   userColumn
	Email      userColumn
	FirstName  userColumn
	LastName   userColumn
	CreatedAt  userColumn
	UpdatedAt  userColumn
	Meta       userColumn
}

// Alias returns the current table alias for the columns set.
func (c userColumns) Alias() string {
	return c.tableAlias
}

// AliasedAs returns a copy of the columns set qualified by tableName.
func (userColumns) AliasedAs(tableName string) userColumns {
	return buildUserColumns(tableName)
}

// Unqualified returns a copy of the columns set without table qualification.
func (c userColumns) Unqualified() userColumns {
	return buildUserColumns("")
}

func buildUserColumn(alias, name string) userColumn {
	return userColumn{
		Expression: psql.Quote(alias, name),
		alias:      alias,
		name:       name,
	}
}

type userColumn struct {
	psql.Expression
	alias string
	name  string
}

// Name returns the unqualified column name.
func (c userColumn) Name() string {
	return c.name
}

// ShouldOmitParens prevents automatic parenthesis wrapping in expression builders.
func (c userColumn) ShouldOmitParens() bool {
	return true
}

// UserSetter is used for insert/upsert/update operations
// All values are optional, and do not have to be set
// Generated columns are not included
type UserSetter struct {
	ID        *string                                `db:"id,pk" `
	Username  *string                                `db:"username" `
	Email     *string                                `db:"email" `
	FirstName *string                                `db:"first_name" `
	LastName  *string                                `db:"last_name" `
	CreatedAt *time.Time                             `db:"created_at" `
	UpdatedAt *time.Time                             `db:"updated_at" `
	Meta      *sql.Null[types.JSON[dto.UserMetaBox]] `db:"meta" `
}

func (s UserSetter) SetColumns() []string {
	vals := make([]string, 0, 8)
	if s.ID != nil {
		vals = append(vals, "id")
	}
	if s.Username != nil {
		vals = append(vals, "username")
	}
	if s.Email != nil {
		vals = append(vals, "email")
	}
	if s.FirstName != nil {
		vals = append(vals, "first_name")
	}
	if s.LastName != nil {
		vals = append(vals, "last_name")
	}
	if s.CreatedAt != nil {
		vals = append(vals, "created_at")
	}
	if s.UpdatedAt != nil {
		vals = append(vals, "updated_at")
	}
	if s.Meta != nil {
		vals = append(vals, "meta")
	}
	return vals
}

func (s UserSetter) Overwrite(t *User) {
	if s.ID != nil {
		t.ID = func() string {
			if s.ID == nil {
				return *new(string)
			}
			return *s.ID
		}()
	}
	if s.Username != nil {
		t.Username = func() string {
			if s.Username == nil {
				return *new(string)
			}
			return *s.Username
		}()
	}
	if s.Email != nil {
		t.Email = func() string {
			if s.Email == nil {
				return *new(string)
			}
			return *s.Email
		}()
	}
	if s.FirstName != nil {
		t.FirstName = func() string {
			if s.FirstName == nil {
				return *new(string)
			}
			return *s.FirstName
		}()
	}
	if s.LastName != nil {
		t.LastName = func() string {
			if s.LastName == nil {
				return *new(string)
			}
			return *s.LastName
		}()
	}
	if s.CreatedAt != nil {
		t.CreatedAt = func() time.Time {
			if s.CreatedAt == nil {
				return *new(time.Time)
			}
			return *s.CreatedAt
		}()
	}
	if s.UpdatedAt != nil {
		t.UpdatedAt = func() time.Time {
			if s.UpdatedAt == nil {
				return *new(time.Time)
			}
			return *s.UpdatedAt
		}()
	}
	if s.Meta != nil {
		t.Meta = func() sql.Null[types.JSON[dto.UserMetaBox]] {
			if s.Meta == nil {
				return *new(sql.Null[types.JSON[dto.UserMetaBox]])
			}
			v := s.Meta
			return *v
		}()
	}
}

func (s *UserSetter) Apply(q *dialect.InsertQuery) {
	q.AppendHooks(func(ctx context.Context, exec bob.Executor) (context.Context, error) {
		return Users.BeforeInsertHooks.RunHooks(ctx, exec, s)
	})

	q.AppendValues(
		bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
			if s.ID == nil {
				return psql.Raw("DEFAULT").WriteSQL(ctx, w, d, start)
			}
			return psql.Arg(func() string {
				if s.ID == nil {
					return *new(string)
				}
				return *s.ID
			}()).WriteSQL(ctx, w, d, start)
		}), bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
			if s.Username == nil {
				return psql.Raw("DEFAULT").WriteSQL(ctx, w, d, start)
			}
			return psql.Arg(func() string {
				if s.Username == nil {
					return *new(string)
				}
				return *s.Username
			}()).WriteSQL(ctx, w, d, start)
		}), bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
			if s.Email == nil {
				return psql.Raw("DEFAULT").WriteSQL(ctx, w, d, start)
			}
			return psql.Arg(func() string {
				if s.Email == nil {
					return *new(string)
				}
				return *s.Email
			}()).WriteSQL(ctx, w, d, start)
		}), bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
			if s.FirstName == nil {
				return psql.Raw("DEFAULT").WriteSQL(ctx, w, d, start)
			}
			return psql.Arg(func() string {
				if s.FirstName == nil {
					return *new(string)
				}
				return *s.FirstName
			}()).WriteSQL(ctx, w, d, start)
		}), bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
			if s.LastName == nil {
				return psql.Raw("DEFAULT").WriteSQL(ctx, w, d, start)
			}
			return psql.Arg(func() string {
				if s.LastName == nil {
					return *new(string)
				}
				return *s.LastName
			}()).WriteSQL(ctx, w, d, start)
		}), bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
			if s.CreatedAt == nil {
				return psql.Raw("DEFAULT").WriteSQL(ctx, w, d, start)
			}
			return psql.Arg(func() time.Time {
				if s.CreatedAt == nil {
					return *new(time.Time)
				}
				return *s.CreatedAt
			}()).WriteSQL(ctx, w, d, start)
		}), bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
			if s.UpdatedAt == nil {
				return psql.Raw("DEFAULT").WriteSQL(ctx, w, d, start)
			}
			return psql.Arg(func() time.Time {
				if s.UpdatedAt == nil {
					return *new(time.Time)
				}
				return *s.UpdatedAt
			}()).WriteSQL(ctx, w, d, start)
		}), bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
			if s.Meta == nil {
				return psql.Raw("DEFAULT").WriteSQL(ctx, w, d, start)
			}
			return psql.Arg(func() sql.Null[types.JSON[dto.UserMetaBox]] {
				if s.Meta == nil {
					return *new(sql.Null[types.JSON[dto.UserMetaBox]])
				}
				v := s.Meta
				return *v
			}()).WriteSQL(ctx, w, d, start)
		}))
}

func (s UserSetter) UpdateMod() bob.Mod[*dialect.UpdateQuery] {
	return um.Set(s.Expressions()...)
}

func (s UserSetter) Expressions(prefix ...string) []bob.Expression {
	exprs := make([]bob.Expression, 0, 8)

	if s.ID != nil {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "id")...),
			psql.Arg(s.ID),
		}})
	}

	if s.Username != nil {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "username")...),
			psql.Arg(s.Username),
		}})
	}

	if s.Email != nil {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "email")...),
			psql.Arg(s.Email),
		}})
	}

	if s.FirstName != nil {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "first_name")...),
			psql.Arg(s.FirstName),
		}})
	}

	if s.LastName != nil {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "last_name")...),
			psql.Arg(s.LastName),
		}})
	}

	if s.CreatedAt != nil {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "created_at")...),
			psql.Arg(s.CreatedAt),
		}})
	}

	if s.UpdatedAt != nil {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "updated_at")...),
			psql.Arg(s.UpdatedAt),
		}})
	}

	if s.Meta != nil {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "meta")...),
			psql.Arg(s.Meta),
		}})
	}

	return exprs
}

// scan.Mapper[*T] without reflection: maps columns to fields by index.
func userScanMapper(ctx context.Context, cols []string) (scan.BeforeFunc, func(any) (*User, error)) {
	// resolve the column positions once per query, not per row
	type target struct {
		idx int
		dst func(o *User) any
	}
	targets := make([]target, 0, 8)
	for i, col := range cols {
		switch col {
		case "id":
			targets = append(targets, target{i, func(o *User) any { return &o.ID }})
		case "username":
			targets = append(targets, target{i, func(o *User) any { return &o.Username }})
		case "email":
			targets = append(targets, target{i, func(o *User) any { return &o.Email }})
		case "first_name":
			targets = append(targets, target{i, func(o *User) any { return &o.FirstName }})
		case "last_name":
			targets = append(targets, target{i, func(o *User) any { return &o.LastName }})
		case "created_at":
			targets = append(targets, target{i, func(o *User) any { return &o.CreatedAt }})
		case "updated_at":
			targets = append(targets, target{i, func(o *User) any { return &o.UpdatedAt }})
		case "meta":
			targets = append(targets, target{i, func(o *User) any { return &o.Meta }})
		}
	}

	return func(row *scan.Row) (any, error) {
			o := new(User)
			for _, t := range targets {
				row.ScheduleScanByIndex(t.idx, t.dst(o))
			}
			return o, nil
		}, func(v any) (*User, error) {
			return v.(*User), nil
		}
}

// FindUser retrieves a single record by primary key
// If cols is empty Find will return all columns.
func FindUser(ctx context.Context, exec bob.Executor, IDPK string, cols ...string) (*User, error) {
	if len(cols) == 0 {
		return Users.Query(
			sm.Where(Users.Columns.ID.EQ(psql.Arg(IDPK))),
		).One(ctx, exec)
	}

	return Users.Query(
		sm.Where(Users.Columns.ID.EQ(psql.Arg(IDPK))),
		sm.Columns(Users.Columns.Only(cols...)),
	).One(ctx, exec)
}

// UserExists checks the presence of a single record by primary key
func UserExists(ctx context.Context, exec bob.Executor, IDPK string) (bool, error) {
	return Users.Query(
		sm.Where(Users.Columns.ID.EQ(psql.Arg(IDPK))),
	).Exists(ctx, exec)
}

// AfterQueryHook is called after User is retrieved from the database
func (o *User) AfterQueryHook(ctx context.Context, exec bob.Executor, queryType bob.QueryType) error {
	var err error

	switch queryType {
	case bob.QueryTypeSelect:
		ctx, err = Users.AfterSelectHooks.RunHooks(ctx, exec, UserSlice{o})
	case bob.QueryTypeInsert:
		ctx, err = Users.AfterInsertHooks.RunHooks(ctx, exec, UserSlice{o})
	case bob.QueryTypeUpdate:
		ctx, err = Users.AfterUpdateHooks.RunHooks(ctx, exec, UserSlice{o})
	case bob.QueryTypeDelete:
		ctx, err = Users.AfterDeleteHooks.RunHooks(ctx, exec, UserSlice{o})
	case bob.QueryTypeMerge:
		ctx, err = Users.AfterMergeHooks.RunHooks(ctx, exec, UserSlice{o})
	}

	return err
}

// primaryKeyVals returns the primary key values of the User
func (o *User) primaryKeyVals() bob.Expression {
	return psql.Arg(o.ID)
}

func (o *User) pkEQ() dialect.Expression {
	return psql.Quote("users", "id").EQ(bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
		return o.primaryKeyVals().WriteSQL(ctx, w, d, start)
	}))
}

// Update uses an executor to update the User
func (o *User) Update(ctx context.Context, exec bob.Executor, s *UserSetter) error {
	v, err := Users.Update(s.UpdateMod(), um.Where(o.pkEQ())).One(ctx, exec)
	if err != nil {
		return err
	}

	o.R = v.R
	*o = *v

	return nil
}

// Delete deletes a single User record with an executor
func (o *User) Delete(ctx context.Context, exec bob.Executor) error {
	_, err := Users.Delete(dm.Where(o.pkEQ())).Exec(ctx, exec)
	return err
}

// Reload refreshes the User using the executor
func (o *User) Reload(ctx context.Context, exec bob.Executor) error {
	o2, err := Users.Query(
		sm.Where(Users.Columns.ID.EQ(psql.Arg(o.ID))),
	).One(ctx, exec)
	if err != nil {
		return err
	}
	o2.R = o.R
	*o = *o2

	return nil
}

// AfterQueryHook is called after UserSlice is retrieved from the database
func (o UserSlice) AfterQueryHook(ctx context.Context, exec bob.Executor, queryType bob.QueryType) error {
	var err error

	switch queryType {
	case bob.QueryTypeSelect:
		ctx, err = Users.AfterSelectHooks.RunHooks(ctx, exec, o)
	case bob.QueryTypeInsert:
		ctx, err = Users.AfterInsertHooks.RunHooks(ctx, exec, o)
	case bob.QueryTypeUpdate:
		ctx, err = Users.AfterUpdateHooks.RunHooks(ctx, exec, o)
	case bob.QueryTypeDelete:
		ctx, err = Users.AfterDeleteHooks.RunHooks(ctx, exec, o)
	case bob.QueryTypeMerge:
		ctx, err = Users.AfterMergeHooks.RunHooks(ctx, exec, o)
	}

	return err
}

func (o UserSlice) pkIN() dialect.Expression {
	if len(o) == 0 {
		return psql.Raw("NULL")
	}

	return psql.Quote("users", "id").In(bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
		pkPairs := make([]bob.Expression, len(o))
		for i, row := range o {
			pkPairs[i] = row.primaryKeyVals()
		}
		return bob.ExpressSlice(ctx, w, d, start, pkPairs, "", ", ", "")
	}))
}

// copyMatchingRows finds models in the given slice that have the same primary key
// then it first copies the existing relationships from the old model to the new model
// and then replaces the old model in the slice with the new model
func (o UserSlice) copyMatchingRows(from ...*User) {
	fromByPK := make(map[string]*User, len(from))
	for _, new := range from {
		// keep the first row for each key, like the nested loop did
		if _, ok := fromByPK[new.ID]; !ok {
			fromByPK[new.ID] = new
		}
	}

	for i, old := range o {
		new, ok := fromByPK[old.ID]
		if !ok {
			continue
		}
		new.R = old.R
		o[i] = new
	}
}

// UpdateMod modifies an update query with "WHERE primary_key IN (o...)"
func (o UserSlice) UpdateMod() bob.Mod[*dialect.UpdateQuery] {
	return bob.ModFunc[*dialect.UpdateQuery](func(q *dialect.UpdateQuery) {
		q.AppendHooks(func(ctx context.Context, exec bob.Executor) (context.Context, error) {
			return Users.BeforeUpdateHooks.RunHooks(ctx, exec, o)
		})

		q.AppendLoader(bob.LoaderFunc(func(ctx context.Context, exec bob.Executor, retrieved any) error {
			var err error
			switch retrieved := retrieved.(type) {
			case *User:
				o.copyMatchingRows(retrieved)
			case []*User:
				o.copyMatchingRows(retrieved...)
			case UserSlice:
				o.copyMatchingRows(retrieved...)
			default:
				// If the retrieved value is not a User or a slice of User
				// then run the AfterUpdateHooks on the slice
				_, err = Users.AfterUpdateHooks.RunHooks(ctx, exec, o)
			}

			return err
		}))

		q.AppendWhere(o.pkIN())
	})
}

// DeleteMod modifies an delete query with "WHERE primary_key IN (o...)"
func (o UserSlice) DeleteMod() bob.Mod[*dialect.DeleteQuery] {
	return bob.ModFunc[*dialect.DeleteQuery](func(q *dialect.DeleteQuery) {
		q.AppendHooks(func(ctx context.Context, exec bob.Executor) (context.Context, error) {
			return Users.BeforeDeleteHooks.RunHooks(ctx, exec, o)
		})

		q.AppendLoader(bob.LoaderFunc(func(ctx context.Context, exec bob.Executor, retrieved any) error {
			var err error
			switch retrieved := retrieved.(type) {
			case *User:
				o.copyMatchingRows(retrieved)
			case []*User:
				o.copyMatchingRows(retrieved...)
			case UserSlice:
				o.copyMatchingRows(retrieved...)
			default:
				// If the retrieved value is not a User or a slice of User
				// then run the AfterDeleteHooks on the slice
				_, err = Users.AfterDeleteHooks.RunHooks(ctx, exec, o)
			}

			return err
		}))

		q.AppendWhere(o.pkIN())
	})
}

// MergeMod modifies a merge query to run BeforeMergeHooks and AfterMergeHooks
// and updates the slice with the returned rows.
func (o UserSlice) MergeMod() bob.Mod[*dialect.MergeQuery] {
	return bob.ModFunc[*dialect.MergeQuery](func(q *dialect.MergeQuery) {
		q.AppendHooks(func(ctx context.Context, exec bob.Executor) (context.Context, error) {
			return Users.BeforeMergeHooks.RunHooks(ctx, exec, o)
		})

		q.AppendLoader(bob.LoaderFunc(func(ctx context.Context, exec bob.Executor, retrieved any) error {
			var err error
			switch retrieved := retrieved.(type) {
			case *User:
				o.copyMatchingRows(retrieved)
			case []*User:
				o.copyMatchingRows(retrieved...)
			case UserSlice:
				o.copyMatchingRows(retrieved...)
			default:
				// If the retrieved value is not a User or a slice of User
				// then run the AfterMergeHooks on the slice
				_, err = Users.AfterMergeHooks.RunHooks(ctx, exec, o)
			}

			return err
		}))
	})
}

func (o UserSlice) UpdateAll(ctx context.Context, exec bob.Executor, vals UserSetter) error {
	if len(o) == 0 {
		return nil
	}

	_, err := Users.Update(vals.UpdateMod(), o.UpdateMod()).All(ctx, exec)
	return err
}

func (o UserSlice) DeleteAll(ctx context.Context, exec bob.Executor) error {
	if len(o) == 0 {
		return nil
	}

	_, err := Users.Delete(o.DeleteMod()).Exec(ctx, exec)
	return err
}

func (o UserSlice) ReloadAll(ctx context.Context, exec bob.Executor) error {
	if len(o) == 0 {
		return nil
	}

	o2, err := Users.Query(sm.Where(o.pkIN())).All(ctx, exec)
	if err != nil {
		return err
	}

	o.copyMatchingRows(o2...)

	return nil
}

// UserGroups starts a query for related objects on user_groups
func (o *User) UserGroups(mods ...bob.Mod[*dialect.SelectQuery]) UserGroupsQuery {
	return UserGroups.Query(append(mods,
		sm.Where(UserGroups.Columns.UserID.EQ(psql.Arg(o.ID))),
	)...)
}

func (os UserSlice) UserGroups(mods ...bob.Mod[*dialect.SelectQuery]) UserGroupsQuery {
	pkID := make(pgtypes.Array[string], 0, len(os))
	for _, o := range os {
		if o == nil {
			continue
		}
		pkID = append(pkID, o.ID)
	}

	PKArgExpr := psql.Any(psql.Cast(psql.Arg(pkID), "uuid[]"))

	return UserGroups.Query(append(mods,
		sm.Where(UserGroups.Columns.UserID.EQ(PKArgExpr)),
	)...)
}

func insertUserUserGroups0(ctx context.Context, exec bob.Executor, userGroups1 []*UserGroupSetter, user0 *User) (UserGroupSlice, error) {
	for i := range userGroups1 {
		userGroups1[i].UserID = func() *string { return &user0.ID }()
	}

	ret, err := UserGroups.Insert(bob.ToMods(userGroups1...)).All(ctx, exec)
	if err != nil {
		return ret, fmt.Errorf("insertUserUserGroups0: %w", err)
	}

	return ret, nil
}

func attachUserUserGroups0(ctx context.Context, exec bob.Executor, count int, userGroups1 UserGroupSlice, user0 *User) (UserGroupSlice, error) {
	setter := &UserGroupSetter{
		UserID: func() *string { return &user0.ID }(),
	}

	err := userGroups1.UpdateAll(ctx, exec, *setter)
	if err != nil {
		return nil, fmt.Errorf("attachUserUserGroups0: %w", err)
	}

	return userGroups1, nil
}

func (user0 *User) InsertUserGroups(ctx context.Context, exec bob.Executor, related ...*UserGroupSetter) error {
	if len(related) == 0 {
		return nil
	}

	var err error

	userGroups1, err := insertUserUserGroups0(ctx, exec, related, user0)
	if err != nil {
		return err
	}

	user0.R.UserGroups = append(user0.R.UserGroups, userGroups1...)

	for _, rel := range userGroups1 {
		rel.R.User = user0
		rel.R.Loaded.User = true
	}
	return nil
}

func (user0 *User) AttachUserGroups(ctx context.Context, exec bob.Executor, related ...*UserGroup) error {
	if len(related) == 0 {
		return nil
	}

	var err error
	userGroups1 := UserGroupSlice(related)

	_, err = attachUserUserGroups0(ctx, exec, len(related), userGroups1, user0)
	if err != nil {
		return err
	}

	user0.R.UserGroups = append(user0.R.UserGroups, userGroups1...)

	for _, rel := range related {
		rel.R.User = user0
		rel.R.Loaded.User = true
	}

	return nil
}

type userWhere[Q psql.Filterable] struct {
	cols      userColumns
	ID        psql.WhereMod[Q, string]
	Username  psql.WhereMod[Q, string]
	Email     psql.WhereMod[Q, string]
	FirstName psql.WhereMod[Q, string]
	LastName  psql.WhereMod[Q, string]
	CreatedAt psql.WhereMod[Q, time.Time]
	UpdatedAt psql.WhereMod[Q, time.Time]
	Meta      psql.WhereNullMod[Q, types.JSON[dto.UserMetaBox]]
	R         userWhereR[Q]
}

func (userWhere[Q]) AliasedAs(alias string) userWhere[Q] {
	return buildUserWhere[Q](buildUserColumns(alias))
}

func buildUserWhere[Q psql.Filterable](cols userColumns) userWhere[Q] {
	return userWhere[Q]{
		cols:      cols,
		ID:        psql.Where[Q, string](cols.ID.Expression),
		Username:  psql.Where[Q, string](cols.Username.Expression),
		Email:     psql.Where[Q, string](cols.Email.Expression),
		FirstName: psql.Where[Q, string](cols.FirstName.Expression),
		LastName:  psql.Where[Q, string](cols.LastName.Expression),
		CreatedAt: psql.Where[Q, time.Time](cols.CreatedAt.Expression),
		UpdatedAt: psql.Where[Q, time.Time](cols.UpdatedAt.Expression),
		Meta:      psql.WhereNull[Q, types.JSON[dto.UserMetaBox]](cols.Meta.Expression),
		R:         userWhereR[Q]{cols: cols},
	}
}

// userWhereR holds the relationship-based filters of
// userWhere under the R namespace — mirroring the model's
// R struct — so they cannot collide with column-based filter fields.
type userWhereR[Q psql.Filterable] struct {
	cols userColumns
}

// HasUserGroups filters parents that have a matching UserGroups using a
// correlated EXISTS subquery (semi-join). Unlike an INNER JOIN it does not
// multiply parent rows, so no DISTINCT is needed. The optional filters are
// applied to the subquery (i.e. to UserGroups).
func (w userWhereR[Q]) HasUserGroups(filters ...bob.Mod[*dialect.SelectQuery]) mods.Where[Q] {
	q := psql.Select(
		sm.Columns(psql.Raw("1")),
		sm.From(UserGroups.NameExpr()),
		sm.Where(UserGroups.Columns.UserID.EQ(w.cols.ID)),
	)
	q.Apply(filters...)
	return mods.Where[Q]{E: psql.Exists(q)}
}

// NULL-tolerant scan buffer for userScanMapperNullable:
// on a LEFT JOIN miss every column comes back NULL, so each field uses the
// nullable version of the column type even when the column itself is NOT NULL.
type userPreloadBuf struct {
	ID        sql.Null[string]
	Username  sql.Null[string]
	Email     sql.Null[string]
	FirstName sql.Null[string]
	LastName  sql.Null[string]
	CreatedAt sql.Null[time.Time]
	UpdatedAt sql.Null[time.Time]
	Meta      sql.Null[types.JSON[dto.UserMetaBox]]
}

// userScanMapperNullable maps the preloaded user
// columns (prefixed with the runtime join alias) without reflection, while
// keeping the LEFT JOIN semantics of the reflection-based mapper: a row whose
// prefixed columns are all NULL yields nil (no child), and NULL values never
// error, they just leave the zero value in the field.
func userScanMapperNullable(prefix string) scan.Mapper[*User] {
	return func(ctx context.Context, cols []string) (scan.BeforeFunc, func(any) (*User, error)) {
		// resolve the column names once per query, not per row
		type target struct {
			idx int
			dst func(b *userPreloadBuf) any
		}
		targets := make([]target, 0, 8)
		for i, col := range cols {
			name, ok := strings.CutPrefix(col, prefix)
			if !ok {
				continue
			}
			switch name {
			case "id":
				targets = append(targets, target{i, func(b *userPreloadBuf) any { return &b.ID }})
			case "username":
				targets = append(targets, target{i, func(b *userPreloadBuf) any { return &b.Username }})
			case "email":
				targets = append(targets, target{i, func(b *userPreloadBuf) any { return &b.Email }})
			case "first_name":
				targets = append(targets, target{i, func(b *userPreloadBuf) any { return &b.FirstName }})
			case "last_name":
				targets = append(targets, target{i, func(b *userPreloadBuf) any { return &b.LastName }})
			case "created_at":
				targets = append(targets, target{i, func(b *userPreloadBuf) any { return &b.CreatedAt }})
			case "updated_at":
				targets = append(targets, target{i, func(b *userPreloadBuf) any { return &b.UpdatedAt }})
			case "meta":
				targets = append(targets, target{i, func(b *userPreloadBuf) any { return &b.Meta }})
			}
		}

		// One scratch buffer reused for every row: before -> scan -> after runs
		// synchronously per row, the scheduled columns are fully overwritten each
		// row, and unselected columns stay zero, so a single buffer preserves the
		// per-row NULL semantics without allocating a buffer per parent row. The
		// returned child (o below) is always freshly allocated, so buf never
		// escapes past the after func.
		buf := new(userPreloadBuf)
		return func(row *scan.Row) (any, error) {
				for _, t := range targets {
					row.ScheduleScanByIndex(t.idx, t.dst(buf))
				}
				return buf, nil
			}, func(link any) (*User, error) {
				buf := link.(*userPreloadBuf)

				// Same rule as the reflection mapper's row validator: the child
				// exists only if at least one of its columns is not NULL. Columns
				// not selected by the query are never scanned and stay invalid,
				// so this check also matches when only a subset is selected.
				if !(buf.ID.Valid) &&
					!(buf.Username.Valid) &&
					!(buf.Email.Valid) &&
					!(buf.FirstName.Valid) &&
					!(buf.LastName.Valid) &&
					!(buf.CreatedAt.Valid) &&
					!(buf.UpdatedAt.Valid) &&
					!(buf.Meta.Valid) {
					return nil, nil
				}

				o := new(User)
				if buf.ID.Valid {
					o.ID = buf.ID.V
				}
				if buf.Username.Valid {
					o.Username = buf.Username.V
				}
				if buf.Email.Valid {
					o.Email = buf.Email.V
				}
				if buf.FirstName.Valid {
					o.FirstName = buf.FirstName.V
				}
				if buf.LastName.Valid {
					o.LastName = buf.LastName.V
				}
				if buf.CreatedAt.Valid {
					o.CreatedAt = buf.CreatedAt.V
				}
				if buf.UpdatedAt.Valid {
					o.UpdatedAt = buf.UpdatedAt.V
				}
				o.Meta = buf.Meta
				return o, nil
			}
	}
}

func (o *User) Preload(name string, retrieved any) error {
	if o == nil {
		return nil
	}

	switch name {
	case "UserGroups":
		rels, ok := retrieved.(UserGroupSlice)
		if !ok {
			return fmt.Errorf("user cannot load %T as %q", retrieved, name)
		}

		o.R.UserGroups = rels
		o.R.Loaded.UserGroups = true

		for _, rel := range rels {
			if rel != nil {
				rel.R.User = o
				rel.R.Loaded.User = true
			}
		}
		return nil
	default:
		return fmt.Errorf("user has no relationship %q", name)
	}
}

type userPreloader struct{}

func buildUserPreloader() userPreloader {
	return userPreloader{}
}

type userThenLoader[Q orm.Loadable] struct {
	UserGroups func(...bob.Mod[*dialect.SelectQuery]) orm.Loader[Q]
}

func buildUserThenLoader[Q orm.Loadable]() userThenLoader[Q] {
	type UserGroupsLoadInterface interface {
		LoadUserGroups(context.Context, bob.Executor, ...bob.Mod[*dialect.SelectQuery]) error
	}

	return userThenLoader[Q]{
		UserGroups: thenLoadBuilder[Q](
			"UserGroups",
			func(ctx context.Context, exec bob.Executor, retrieved UserGroupsLoadInterface, mods ...bob.Mod[*dialect.SelectQuery]) error {
				return retrieved.LoadUserGroups(ctx, exec, mods...)
			},
		),
	}
}

// LoadUserGroups loads the user's UserGroups into the .R struct
func (o *User) LoadUserGroups(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if o == nil {
		return nil
	}

	// Reset the relationship
	o.R.UserGroups = nil
	o.R.Loaded.UserGroups = false

	related, err := o.UserGroups(mods...).All(ctx, exec)
	if err != nil {
		return err
	}

	for _, rel := range related {
		rel.R.User = o
		rel.R.Loaded.User = true
	}

	o.R.UserGroups = related
	o.R.Loaded.UserGroups = true
	return nil
}

// LoadUserGroups loads the user's UserGroups into the .R struct
func (os UserSlice) LoadUserGroups(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if len(os) == 0 {
		return nil
	}

	userGroups, err := os.UserGroups(mods...).All(ctx, exec)
	if err != nil {
		return err
	}

	for _, o := range os {
		if o == nil {
			continue
		}

		o.R.UserGroups = nil
		o.R.Loaded.UserGroups = true
	}
	// O(N+M) stitch via a map keyed by the join column (key -> []parent; was O(N*M)).
	userByKey := make(map[string][]*User, len(os))
	for _, o := range os {
		if o == nil {
			continue
		}

		userByKey[o.ID] = append(userByKey[o.ID], o)
	}

	for _, rel := range userGroups {

		owners, ok := userByKey[rel.UserID]
		if !ok {
			continue
		}

		for _, o := range owners {

			rel.R.User = o
			rel.R.Loaded.User = true

			o.R.UserGroups = append(o.R.UserGroups, rel)

		}
	}

	return nil
}

// userC is where relationship counts are stored.
type userC struct {
	UserGroups *int64
}

// PreloadCount sets a count in the C struct by name
func (o *User) PreloadCount(name string, count int64) error {
	if o == nil {
		return nil
	}

	switch name {
	case "UserGroups":
		o.C.UserGroups = &count
	}
	return nil
}

type userCountPreloader struct {
	UserGroups func(...bob.Mod[*dialect.SelectQuery]) psql.Preloader
}

func buildUserCountPreloader() userCountPreloader {
	return userCountPreloader{
		UserGroups: func(mods ...bob.Mod[*dialect.SelectQuery]) psql.Preloader {
			return countPreloader[*User]("UserGroups", func(parent string) bob.Expression {
				// Build a correlated subquery: (SELECT COUNT(*) FROM related WHERE fk = parent.pk)
				if parent == "" {
					parent = Users.Alias()
				}

				subqueryMods := []bob.Mod[*dialect.SelectQuery]{
					sm.Columns(psql.Raw("count(*)")),

					sm.From(UserGroups.NameAsExpr()),
					sm.Where(psql.Quote(UserGroups.Alias(), "user_id").EQ(psql.Quote(parent, "id"))),
				}
				subqueryMods = append(subqueryMods, mods...)
				return psql.Group(psql.Select(subqueryMods...).Expression)
			})
		},
	}
}

type userCountThenLoader[Q orm.Loadable] struct {
	UserGroups func(...bob.Mod[*dialect.SelectQuery]) orm.Loader[Q]
}

func buildUserCountThenLoader[Q orm.Loadable]() userCountThenLoader[Q] {
	type UserGroupsCountInterface interface {
		LoadCountUserGroups(context.Context, bob.Executor, ...bob.Mod[*dialect.SelectQuery]) error
	}

	return userCountThenLoader[Q]{
		UserGroups: countThenLoadBuilder[Q](
			"UserGroups",
			func(ctx context.Context, exec bob.Executor, retrieved UserGroupsCountInterface, mods ...bob.Mod[*dialect.SelectQuery]) error {
				return retrieved.LoadCountUserGroups(ctx, exec, mods...)
			},
		),
	}
}

// LoadCountUserGroups loads the count of UserGroups into the C struct
func (o *User) LoadCountUserGroups(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if o == nil {
		return nil
	}

	count, err := o.UserGroups(mods...).Count(ctx, exec)
	if err != nil {
		return err
	}

	o.C.UserGroups = &count
	return nil
}

// LoadCountUserGroups loads the count of UserGroups for a slice in a single batch query
func (os UserSlice) LoadCountUserGroups(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if len(os) == 0 {
		return nil
	}

	// Build the IN arg expression from parent PKs

	pkID := make(pgtypes.Array[string], 0, len(os))
	for _, o := range os {
		if o == nil {
			continue
		}
		pkID = append(pkID, o.ID)
	}
	PKArgExpr := psql.Any(psql.Cast(psql.Arg(pkID), "uuid[]"))

	// countResult holds one scanned row from the batch count query.
	// FK columns are aliased to the parent PK column names for direct map lookup.
	type countResult struct {
		ID    string
		Count int64
	}

	batchMods := []bob.Mod[*dialect.SelectQuery]{
		// SELECT fk AS parent_pk, count(*)
		sm.Columns(
			UserGroups.Columns.UserID.As("id"),
			psql.Raw("count(*) as count"),
		),
		// Single-hop: FROM related table directly
		sm.From(UserGroups.NameAsExpr()),

		// WHERE fk IN (parent PKs) — psql single-column FK uses `= ANY(array)` (see PKArgExpr above)
		sm.Where(UserGroups.Columns.UserID.EQ(PKArgExpr)),
		// GROUP BY fk columns
		sm.GroupBy(UserGroups.Columns.UserID),
	}
	batchMods = append(batchMods, mods...)

	results, err := bob.All(ctx, exec,
		psql.Select(batchMods...),
		scan.StructMapper[countResult](),
	)
	if err != nil {
		return err
	}

	// Single-column FK: direct map lookup
	countMap := make(map[string]int64, len(results))
	for _, r := range results {
		countMap[r.ID] = r.Count
	}
	for _, o := range os {
		if o == nil {
			continue
		}
		count := countMap[o.ID]
		o.C.UserGroups = &count
	}

	return nil
}

type userJoins[Q dialect.Joinable] struct {
	typ        string
	UserGroups modAs[Q, userGroupColumns]
}

func (j userJoins[Q]) aliasedAs(alias string) userJoins[Q] {
	return buildUserJoins[Q](buildUserColumns(alias), j.typ)
}

func buildUserJoins[Q dialect.Joinable](cols userColumns, typ string) userJoins[Q] {
	return userJoins[Q]{
		typ: typ,
		UserGroups: modAs[Q, userGroupColumns]{
			c: UserGroups.Columns,
			f: func(to userGroupColumns) bob.Mod[Q] {
				mods := make(mods.QueryMods[Q], 0, 1)

				{
					mods = append(mods, dialect.Join[Q](typ, UserGroups.NameExpr().As(to.Alias())).On(
						to.UserID.EQ(cols.ID),
					))
				}

				return mods
			},
		},
	}
}
